/**
 * Auth action types
 * */

// REGISTER
export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

// LOGIN
export const DO_LOGIN = 'DO_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// LOGOUT
export const LOGOUT = 'LOGOUT';

// ACTIVATE
export const DO_ACTIVATE = 'DO_ACTIVATE';
export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS';
export const ACTIVATE_ERROR = 'ACTIVATE_ERROR';

// INFO
export const DO_FETCH_INFO = 'DO_FETCH_INFO';
export const FETCH_INFO_SUCCESS = 'FETCH_INFO_SUCCESS';
export const FETCH_INFO_ERROR = 'FETCH_INFO_ERROR';

// FORGOT PASS
export const DO_FORGOT_INIT = 'DO_FORGOT_INIT';
export const FORGOT_INIT_SUCCESS = 'FORGOT_INIT_SUCCESS';
export const FORGOT_INIT_ERROR = 'FORGOT_INIT_ERROR';

// CHANGE PASS
export const DO_CHANGE_PASS = 'DO_CHANGE_PASS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_ERROR = 'CHANGE_PASS_ERROR';

// FETCH BALANCE
export const DO_FETCH_BALANCE = 'DO_FETCH_BALANCE';
export const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS';
export const FETCH_BALANCE_ERROR = 'FETCH_BALANCE_ERROR';
