// fetch list
export const FETCH_ALL_BALANCE = 'FETCH_ALL_BALANCE';
export const FETCH_ALL_BALANCE_SUCCESS = 'FETCH_ALL_BALANCE_SUCCESS';
export const FETCH_ALL_BALANCE_ERROR = 'FETCH_ALL_BALANCE_ERROR';

// fetch SELLER balance
export const FETCH_SELLER_BALANCE = 'FETCH_SELLER_BALANCE';
export const FETCH_SELLER_BALANCE_SUCCESS = 'FETCH_SELLER_BALANCE_SUCCESS';
export const FETCH_SELLER_BALANCE_ERROR = 'FETCH_SELLER_BALANCE_ERROR';

// create deposit
export const CREATE_DEPOSIT = 'CREATE_DEPOSIT';
export const CREATE_DEPOSIT_SUCCESS = 'CREATE_DEPOSIT_SUCCESS';
export const CREATE_DEPOSIT_ERROR = 'CREATE_DEPOSIT_ERROR';

// update deposit 
export const UPDATE_DEPOSIT = 'UPDATE_DEPOSIT';
export const UPDATE_DEPOSIT_SUCCESS = 'UPDATE_DEPOSIT_SUCCESS';
export const UPDATE_DEPOSIT_ERROR = 'UPDATE_DEPOSIT_ERROR';

// delete deposit
export const DELETE_DEPOSIT = 'DELETE_DEPOSIT';
export const DELETE_DEPOSIT_SUCCESS = 'DELETE_DEPOSIT_SUCCESS';
export const DELETE_DEPOSIT_ERROR = 'DELETE_DEPOSIT_ERROR';

export const RESET_ERROR = 'RESET_ERROR';