/**
 * Dashboard action types
 * */

// FETCH STATISTIC
export const DO_FETCH_STATISTIC = 'DO_FETCH_STATISTIC';
export const FETCH_STATISTIC_SUCCESS = 'FETCH_STATISTIC_SUCCESS';
export const FETCH_STATISTIC_ERROR = 'FETCH_STATISTIC_ERROR';

// FETCH URGENT NOTE
export const DO_FETCH_URGENT_NOTE = 'DO_FETCH_URGENT_NOTE';
export const FETCH_URGENT_NOTE_SUCCESS = 'FETCH_URGENT_NOTE_SUCCESS';
export const FETCH_URGENT_NOTE_ERROR = 'FETCH_URGENT_NOTE_ERROR';

// FETCH TOP 10 PR
export const DO_FETCH_TOP_PRODUCT = 'DO_FETCH_TOP_PRODUCT';
export const FETCH_TOP_PRODUCT_SUCCESS = 'FETCH_TOP_PRODUCT_SUCCESS';
export const FETCH_TOP_PRODUCT_ERROR = 'FETCH_TOP_PRODUCT_ERROR';

// FETCH STATUS
export const DO_FETCH_STATUS = 'DO_FETCH_STATUS';
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const FETCH_STATUS_ERROR = 'FETCH_STATUS_ERROR';
