/**
 * Users action types
 * */


// FETCH ALL NEWS
export const DO_FETCH_ALL_NEWS = 'DO_FETCH_ALL_NEWS';
export const FETCH_ALL_NEWS_SUCCESS = 'FETCH_ALL_NEWS_SUCCESS';
export const FETCH_ALL_NEWS_ERROR = 'FETCH_ALL_NEWS_ERROR';


// FETCH LAST 10 NEWS
export const DO_FETCH_TOP_NEWS = 'DO_FETCH_TOP_NEWS';
export const FETCH_TOP_NEWS_SUCCESS = 'FETCH_TOP_NEWS_SUCCESS';
export const FETCH_TOP_NEWS_ERROR = 'FETCH_TOP_NEWS_ERROR';

// CREATE NEW
export const DO_CREATE_NEW = 'DO_CREATE_NEW';
export const CREATE_NEW_SUCCESS = 'CREATE_NEW_SUCCESS';
export const CREATE_NEW_ERROR = 'CREATE_NEW_ERROR';

// UPDATE NEW
export const DO_EDIT_NEW = 'DO_EDIT_NEW';
export const EDIT_NEW_SUCCESS = 'EDIT_NEW_SUCCESS';
export const EDIT_NEW_ERROR = 'EDIT_NEW_ERROR';


// DELETE NEW
export const DO_DELETE_NEW = 'DO_DELETE_NEW';
export const DELETE_NEW_SUCCESS = 'DELETE_NEW_SUCCESS';
export const DELETE_NEW_ERROR = 'DELETE_NEW_ERROR';



