/**
 * Profile action types
 * */


// FETCH ALL NOTIFICATION SETTING
export const DO_FETCH_ALL_NOTIFICATION_SETTING = 'DO_FETCH_ALL_NOTIFICATION_SETTING';
export const FETCH_ALL_NOTIFICATION_SETTING_SUCCESS = 'FETCH_ALL_NOTIFICATION_SETTING_SUCCESS';
export const FETCH_ALL_NOTIFICATION_SETTING_ERROR = 'FETCH_ALL_NOTIFICATION_SETTING_ERROR';

// FETCH ALL CONTENT SETTING
export const DO_FETCH_ALL_CONTENT_SETTING = 'DO_FETCH_ALL_CONTENT_SETTING';
export const FETCH_ALL_CONTENT_SETTING_SUCCESS = 'FETCH_ALL_CONTENT_SETTING_SUCCESS';
export const FETCH_ALL_CONTENT_SETTING_ERROR = 'FETCH_ALL_CONTENT_SETTING_ERROR';

// UPDATE  NOTIFICATION SETTING
export const DO_EDIT_NOTIFICATION_SETTING = 'DO_EDIT_NOTIFICATION_SETTING';
export const EDIT_NOTIFICATION_SETTING_SUCCESS = 'EDIT_NOTIFICATION_SETTING_SUCCESS';
export const EDIT_NOTIFICATION_SETTING_ERROR = 'EDIT_NOTIFICATION_SETTING_ERROR';

// UPDATE  CONTENT SETTING
export const DO_EDIT_CONTENT_SETTING = 'DO_EDIT_CONTENT_SETTING';
export const EDIT_CONTENT_SETTING_SUCCESS = 'EDIT_CONTENT_SETTING_SUCCESS';
export const EDIT_CONTENT_SETTING_ERROR = 'EDIT_CONTENT_SETTING_ERROR';

// UPDATE USER INFO
export const DO_EDIT_USER_INFO = 'DO_EDIT_USER_INFO';
export const EDIT_USER_INFO_SUCCESS = 'EDIT_USER_INFO_SUCCESS';
export const EDIT_USER_INFO_ERROR = 'EDIT_USER_INFO_ERROR';

// UPDATE PASSWORD
export const DO_EDIT_PASS = 'DO_EDIT_PASS';
export const EDIT_PASS_SUCCESS = 'EDIT_PASS_SUCCESS';
export const EDIT_PASS_ERROR = 'EDIT_PASS_ERROR';

