package com.goofinity.pgc_service.enums;

import lombok.Getter;

public enum CarrierEnum {
    C_DHL("DHL Express", "dhl", "http://www.dhl.com/"),
    C_UPS("UPS", "ups", "http://www.ups.com/"),
    C_FEDEX("Fedex", "fedex", "http://www.fedex.com/"),
    C_TNT("TNT", "tnt", "http://www.tnt.com/"),
    C_CHINA_EMS("China EMS", "china-ems", "http://www.ems.com.cn/english.html"),
    C_CHINA_POST("China Post", "china-post", "http://yjcx.ems.com.cn/qps/yjcx"),
    C_SINGAPORE_POST("Singapore Post", "singapore-post", "http://www.singpost.com/"),
    C_SINGAPORE_SPEEDPOST("Singapore Speedpost", "singapore-speedpost", "http://www.speedpost.com.sg/"),
    C_HONG_KONG_POST("Hong Kong Post", "hong-kong-post", "http://www.hongkongpost.hk"),
    C_SWISS_POST("Swiss Post", "swiss-post", "https://www.post.ch/"),
    C_USPS("USPS", "usps", "https://www.usps.com/"),
    C_PARCEL_FORCE("Parcel Force", "parcel-force", "http://www.parcelforce.com/"),
    C_POSTNL_PARCELS("Netherlands Post - PostNL", "postnl-parcels", "http://www.postnl.post/"),
    C_NETHERLANDS_POST("Netherlands Post", "netherlands-post", "http://parcels-uk.tntpost.com/"),
    C_AUSTRALIA_POST("Australia Post", "australia-post", "http://auspost.com.au/"),
    C_AUSTRALIA_EMS("Australia EMS", "australia-ems", "http://auspost.com.au/"),
    C_CANADA_POST("Canada Post", "canada-post", "http://www.canadapost.ca/"),
    C_NEW_ZEALAND_POST("New Zealand Post", "new-zealand-post", "http://www.nzpost.co.nz/"),
    C_BELGIUM_POST("Bpost", "belgium-post", "http://www.bpost2.be/bpostinternational/track_trace/find.php"),
    C_BRAZIL_CORREIOS("Brazil Correios", "brazil-correios", "http://www.correios.com.br/"),
    C_RUSSIAN_POST("Russian Post", "russian-post", "https://pochta.ru/"),
    C_SWEDEN_POSTEN("Sweden Posten", "sweden-posten", "http://www.posten.se/"),
    C_LAPOSTE("La Poste", "laposte", "http://www.laposte.fr"),
    C_CHRONOPOST("France EMS - Chronopost", "chronopost", "http://www.chronopost.fr/"),
    C_COLISSIMO("Colissimo", "colissimo", "http://www.colissimo.fr/"),
    C_POSTE_ITALIANE("Poste Italiane", "poste-italiane", "http://www.poste.it/"),
    C_INDIA_POST("India Post", "india-post", "http://www.indiapost.gov.in/"),
    C_MAGYAR_POSTA("Magyar Posta", "magyar-posta", "http://posta.hu/"),
    C_YANWEN("YANWEN", "yanwen", "http://www.yw56.com.cn/english/index.aspx"),
    C_DHL_GERMANY("Deutsche Post DHL", "dhl-germany", "http://www.dhl.de/"),
    C_AN_POST("An Post", "an-post", "http://www.anpost.ie/"),
    C_DHLPARCEL_NL("DHL Parcel Netherlands", "dhlparcel-nl", "https://www.dhlparcel.nl/"),
    C_DHL_POLAND("DHL Poland Domestic", "dhl-poland", "http://www.dhl.com.pl/"),
    C_DHL_ES("DHL Spain Domestic", "dhl-es", "http://www.dhl.es/"),
    C_CORREOS_MEXICO("Mexico Post", "correos-mexico", "http://www.correosdemexico.gob.mx/"),
    C_POSTEN_NORGE("Posten Norge", "posten-norge", "http://www.posten.no/"),
    C_TNT_IT("TNT Italy", "tnt-it", "http://www.tnt.it/"),
    C_TNT_FR("TNT France", "tnt-fr", "http://www.tnt.fr/"),
    C_CTT("Portugal Post - CTT", "ctt", "http://www.ctt.pt/"),
    C_SOUTH_AFRICA_POST("South African Post Office", "south-africa-post", "http://www.postoffice.co.za/"),
    C_CORREOS_SPAIN("Correos Spain", "correos-spain", "http://www.correos.es/"),
    C_TAIWAN_POST("Chunghwa POST", "taiwan-post", "https://ipost.post.gov.tw/"),
    C_UKRAINE_POST("Ukraine Post", "ukraine-post", "http://ukrposhta.ua/"),
    C_UKRAINE_EMS("Ukraine EMS", "ukraine-ems", "http://dpsz.ua/"),
    C_EMIRATES_POST("Emirates Post", "emirates-post", "http://www.epg.gov.ae/"),
    C_URUGUAY_POST("Uruguay Post", "uruguay-post", "http://www.correo.com.uy/"),
    C_JAPAN_POST("Japan Post", "japan-post", "http://www.post.japanpost.jp/"),
    C_POSTA_ROMANA("Poșta Română", "posta-romana", "http://www.posta-romana.ro/"),
    C_KOREA_POST("Korea Post", "korea-post", "http://www.epost.go.kr/"),
    C_GREECE_POST("ELTA Hellenic Post", "greece-post", "http://www.elta.gr/"),
    C_DEUTSCHE_POST("Deutsche Post", "deutsche-post", "http://www.deutschepost.de/"),
    C_CZECH_POST("Česká Pošta", "czech-post", "http://www.ceskaposta.cz/"),
    C_CORREOS_CHILE("Correos Chile", "correos-chile", "http://www.correos.cl/"),
    C_ALAND_POST("Åland Post", "aland-post", "http://www.posten.ax/"),
    C_MACAO_POST("Macao Post", "macao-post", "http://www.macaupost.gov.mo/"),
    C_WISHPOST("WishPost", "wishpost", "https://www.wishpost.cn"),
    C_PFCEXPRESS("PFC Express", "pfcexpress", "http://www.pfcexpress.com/"),
    C_YUNEXPRESS("Yun Express", "yunexpress", "http://www.yunexpress.com/"),
    C_CNEXPS("CNE Express", "cnexps", "http://tracking.cne.com/cnexx/15/d.htm"),
    C_BUYLOGIC("Buylogic", "buylogic", "http://www.buylogic.cc/"),
    C_4PX("4PX", "4px", "http://express.4px.com/"),
    C_ANJUN("Anjun Logistics", "anjun", "http://www.szanjun.com"),
    C_J_NET("J-NET Express", "j-net", "http://www.j-net.cn/"),
    C_MIUSON_INTERNATIONAL("Miuson Express", "miuson-international", "http://www.miuson.net/cn/home/"),
    C_SFB2C("SF International", "sfb2c", "http://intl.sf-express.com/"),
    C_SF_EXPRESS("S.F Express", "sf-express", "http://www.sf-express.com"),
    C_STO("STO Express", "sto", "http://www.sto.cn/"),
    C_YTO("YTO Express", "yto", "http://www.yto.net.cn/"),
    C_TTKD("TTKD Express", "ttkd", "http://www.ttkdex.com/"),
    C_JD("JD Express", "jd", "http://www.jd-ex.com/"),
    C_ZTO("ZTO Express", "zto", "http://www.zto.cn/"),
    C_ZJS_EXPRESS("ZJS International", "zjs-express", "http://www.zjs.com.cn/"),
    C_YUNDA("Yunda Express", "yunda", "http://yundaex.com/cn/index.php"),
    C_DEPPON("DEPPON", "deppon", "http://www.deppon.com/"),
    C_XQWL("XQ Express", "xqwl", "http://www.xqkjwl.com/"),
    C_CHUKOU1("Chukou1 Logistics", "chukou1", "http://www.chukou1.com"),
    C_XRU("XRU", "xru", "http://www.xru.com/"),
    C_RUSTON("Ruston", "ruston", "http://www.ruston.cc"),
    C_QFKD("QFKD Express", "qfkd", "http://www.qfkd.com.cn"),
    C_NANJINGWOYUAN("Nanjing Woyuan", "nanjingwoyuan", "http://www.nanjingwoyuan.com/"),
    C_HHEXP("Hua Han Logistics", "hhexp", "http://www.hh-exp.com/"),
    C_FLYTEXPRESS("Flyt Express", "flytexpress", "http://www.flytexpress.com/"),
    C_AL8856("Ali Business Logistics", "al8856", "http://www.al8856.com/"),
    C_JCEX("JCEX", "jcex", "http://www.jcex.com/"),
    C_DPE_EXPRESS("DPE Express", "dpe-express", "http://www.dpe.net.cn/"),
    C_LWEHK("LWE", "lwehk", "http://www.lwe.com.hk/"),
    C_EQUICK_CN("Equick China", "equick-cn", "http://www.equick.cn/"),
    C_CUCKOOEXPRESS("Cuckoo Express", "cuckooexpress", "http://www.cuckooexpress.com/"),
    C_DWZ("DWZ Express", "dwz", "http://www.dwz56.com/"),
    C_TAKESEND("Takesend Logistics", "takesend", "http://www.takesend.com/"),
    C_CAINIAO("Aliexpress Standard Shipping", "cainiao", "https://global.cainiao.com/"),
    C_TGX("TGX", "tgx", "http://hk.kerryexpress.com/"),
    C_1DLEXPRESS("1DL Express", "1dlexpress", "www.1dlexpress.com"),
    C_IMILE("iMile", "imile", "http://mweb.imile.com/#/home"),
    C_AUS("Ausworld Express", "aus", "http://www.aus-express.com/"),
    C_SXEXPRESS("SX-Express", "sxexpress", "http://www.sxexpress.com.au"),
    C_UVAN("UVAN Express", "uvan", "http://www.uvan56.com"),
    C_CSD("CSD Express", "csd", "http://www.csdexpress.com"),
    C_SRI_LANKA_POST("Sri Lanka Post", "sri-lanka-post", "http://www.slpost.gov.lk/"),
    C_EWE("EWE Global Express", "ewe", "https://www.ewe.com.au"),
    C_SUDAN_POST("Sudan Post", "sudan-post", "http://www.sudapost.com/"),
    C_DEX_I("DEX-I", "dex-i", "http://www.dex-i.com/"),
    C_NIPPON("Nippon Express", "nippon", "https://www.nittsu.co.jp/"),
    C_COSCO("COSCO eGlobal", "cosco", "http://www.cosco-eglobal.com/"),
    C_LOGISTICS("WEL", "logistics", "http://www.we-logistics.com/"),
    C_NINJAVAN_VN("Ninja Van Vietnam", "ninjavan-vn", "https://www.ninjavan.co/vn-vn"),
    C_SPEEDEE("Spee-Dee Delivery", "speedee", "http://speedeedelivery.com/"),
    C_SYRIAN_POST("Syrian Post", "syrian-post", "http://www.syrianpost.gov.sy/"),
    C_RAIDEREX("RaidereX", "raiderex", "http://raiderex.com/"),
    C_ALLEKURIER("allekurier", "allekurier", "https://allekurier.pl/sledzenie"),
    C_GUANGCHI("GuangChi Express", "guangchi", "http://www.litped.com"),
    C_LPEXPRESS("LP Express", "lpexpress", "https://www.lpexpress.lt/en/home/"),
    C_UN_LINE("Un-line", "un-line", "http://www.un-line.com/"),
    C_RZYEXPRESS("RZY Express", "rzyexpress", "http://rzyexpress.com.sg/"),
    C_TRANSRUSH("Transrush", "transrush", "http://www.transrush.com/"),
    C_VENIPAK("Venipak", "venipak", "https://www.venipak.lt/en/"),
    C_TANZANIA_POST("Tanzania Post", "tanzania-post", "http://www.posta.co.tz/"),
    C_STE56("Suteng Logistics", "ste56", "http://www.ste56.com/"),
    C_BAB_RU("BAB international", "bab-ru", "http://www.bab-ru.com/"),
    C_THAILAND_POST("Thailand Post", "thailand-post", "http://www.thailandpost.co.th/"),
    C_AIRPAK_EXPRESS("Airpak Express", "airpak-express", "http://www.airpak-express.com/"),
    C_WINIT("Winit", "winit", "http://www.winit.com.cn/en"),
    C_BDM("BDM Corriere espresso", "bdm", "https://www.bdmnet.it/tracking/"),
    C_TOGO_POST("Togo Post", "togo-post", "http://www.laposte.tg/"),
    C_QEXPRESS("QEXPRESS", "qexpress", "http://www.qexpress.co.nz/"),
    C_CNILINK("CNILINK", "cnilink", "https://cnilink.com/trace.html"),
    C_SZENDEX("Szendex", "szendex", "https://www.szendex.com"),
    C_TONGA_POST("Tonga Post", "tonga-post", "http://www.tongapost.to/"),
    C_LBCEXPRESS("LBC Express", "lbcexpress", "http://www.lbcexpress.com/"),
    C_360ZEBRA("360zebra", "360zebra", "http://zpd.360zebra.com/track/parcelview#/"),
    C_SPOTON("Spoton Logistics", "spoton", "https://web1.spoton.co.in/spotoncontracker.html"),
    C_TCAT_CN("Smartcat", "tcat-cn", ""),
    C_CHINZ56("Chinz Logistics", "chinz56", "http://www.chinz56.co.nz/"),
    C_HKDEXPRESS("HKD", "hkdexpress", "https://hkdexpress.com.au/pages/tracking"),
    C_TUNISIA_POST("Tunisia Post", "tunisia-post", "http://www.poste.tn/"),
    C_PANDULOGISTICS("Pandu Logistics", "pandulogistics", "http://pandulogistics.com/"),
    C_AUEXPRESS("Auexpress", "auexpress", "http://www.auexpress.com.au"),
    C_DACHSER("Dachser", "dachser", "https://elogistics.dachser.com"),
    C_PITNEYBOWES("Pitney Bowes", "pitneybowes", "https://pitneybowes.shipment.co/track/"),
    C_TURKEY_POST("Turkey Post", "turkey-post", "http://www.ptt.gov.tr/"),
    C_DPD_HK("DPD(HK)", "dpd-hk", "http://dpdgroup.hk/Tracking.htm"),
    C_FEDEX_UK("FedEx UK", "fedex-uk", "http://www.fedex.com/gb/ukservices/"),
    C_TOPYOU("TopYou", "topyou", "http://www.szty56.com/"),
    C_DPD_BE("DPD Belgium", "dpd-be", "https://www.dpd.com/be/en/"),
    C_TUVALU_POST("Tuvalu Post", "tuvalu-post", "http://www.tuvalupost.tv/"),
    C_UGANDA_POST("Uganda Post", "uganda-post", "http://www.ugapost.co.ug/"),
    C_COLLECTPLUS("Collect+", "collectplus", "https://www.collectplus.co.uk/"),
    C_ZTKY("Zhongtie Logistics", "ztky", "http://www.ztky.com/"),
    C_JDPPLUS("Jdpplus", "jdpplus", "http://www.jdpplus.com"),
    C_SAP_EXPRESS("SAP Express", "sap-express", "https://www.sap-express.id/layanan/tracking/track"),
    C_TNT_CLICK("TNT Click", "tnt-click", "https://www.tnt-click.it/"),
    C_SKYNETWORLDWIDE_UK("Skynet Worldwide Express UK", "skynetworldwide-uk", "https://www.skynetworldwide.com/"),
    C_IDADA56("Dada logistic", "idada56", "http://www.idada56.com/"),
    C_SHOWL("Showl", "showl", "http://www.showl.net/"),
    C_V_XPRESS("V-Xpress", "v-xpress", "http://vxpress.in/"),
    C_RUFENGDA("Rufengda", "rufengda", "http://www.rufengda.com"),
    C_HERMES("Hermesworld", "hermes", "https://www.hermesworld.com/en/"),
    C_JERSEY_POST("Jersey Post", "jersey-post", "http://www.jerseypost.com/track/"),
    C_SENDLE("Sendle", "sendle", "https://www.sendle.com/"),
    C_GDWSE("WSE Logistics", "gdwse", "http://www.gdwse.com/"),
    C_DHL_UK("DHL Parcel UK", "dhl-uk", "https://track.dhlparcel.co.uk/"),
    C_NIGHTLINE("Nightline", "nightline", "http://www.nightline.ie/"),
    C_BOMBINO_EXPRESS("Bombino Express", "bombino-express", "http://www.bombinoexp.com/"),
    C_KINGRUNS("KINGRUNS", "kingruns", "http://www.kingruns.com/tms_track.php"),
    C_TARRIVE("TONGDA Global", "tarrive", "http://www.tarrive.com/"),
    C_MAILAMERICAS("MailAmericas", "mailamericas", "http://www.mailamericas.com/"),
    C_NINJAVAN_MY("Ninja Van Malaysia", "ninjavan-my", "https://www.ninjavan.co/en-my"),
    C_SZYN("YingNuo Supply Chain", "szyn", ""),
    C_UZBEKISTAN_POST("Uzbekistan Post", "uzbekistan-post", "http://www.pochta.uz/"),
    C_APC("APC Postal Logistics", "apc", "http://www.apc-pli.com/"),
    C_LEXSHIP("Lexship", "lexship", "https://www.lexship.com/track.php"),
    C_FAR800("Far International Logistics", "far800", "https://www.far800.com/"),
    C_WHISTL("Whistl", "whistl", "https://trackmyitem.whistl.co.uk/"),
    C_VANUATU_POST("Vanuatu Post", "vanuatu-post", "http://www.vanuatupost.vu/"),
    C_NEWGISTICS("Newgistics", "newgistics", "http://newgistics.com/"),
    C_DHL_PARCEL_NL("DHL Netherlands", "dhl-parcel-nl", "http://www.dhl.nl/"),
    C_NINJAXPRESS("Ninja Van Indonesia", "ninjaxpress", "https://www.ninjaxpress.co/"),
    C_ORGANEDS("OrangeDS", "organeds", "https://tracking.orangedsinc.com/"),
    C_DXDELIVERY("DX Delivery", "dxdelivery", "https://www.dxdelivery.com"),
    C_REDPACK_MEXICO("Redpack Mexico", "redpack-mexico", "http://www.redpack.com.mx/"),
    C_OLD_DOMINION("Old Dominion Freight Line", "old-dominion", "http://www.odfl.com/Home/"),
    C_ROADBULL("Roadbull Logistics", "roadbull", "http://www.roadbull.com"),
    C_NINJAVAN_PH("Ninja Van Philippines", "ninjavan-ph", "https://www.ninjavan.co/en-ph"),
    C_VIETNAM_POST("Vietnam Post", "vietnam-post", "http://www.vnpost.vn/"),
    C_DHL_BENELUX("DHL Benelux", "dhl-benelux", "http://www.dhl.nl/"),
    C_HUILOGISTICS("Hui Logistics", "huilogistics", "http://huilogistics.com/index.html"),
    C_ESTES("Estes", "estes", "http://www.estes-express.com/"),
    C_NINJAVAN_TH("Ninja Van Thailand", "ninjavan-th", "https://www.ninjavan.co/th-th"),
    C_PJBEST("Pinjun Express", "pjbest", "http://www.pjbest.com/index"),
    C_CHANGJIANGEXPRESS("changjiangexpress", "changjiangexpress", ""),
    C_YEMEN_POST("Yemen Post", "yemen-post", "http://www.yemenpost.net/"),
    C_SUPEROZ("SuperOZ Logistics", "superoz", "http://www.superoz.com.au/track.html"),
    C_ZAMBIA_POST("Zambia Post", "zambia-post", "http://www.zampost.com.zm/"),
    C_SAICHENG("Sai Cheng Logistics", "saicheng", "http://http://en.saichenglogistics.com/index.html"),
    C_LEOPARDSCHINA("Leopards Express", "leopardschina", "http://www.leopardschina.com/"),
    C_CSE("cse", "cse", "https://cse.ru/track.php"),
    C_ZIMBABWE_POST("Zimbabwe Post", "zimbabwe-post", "http://www.zimpost.co.zw/"),
    C_BEEBIRD("Beebird Logistics", "beebird", "https://beebird.com.au/tracking"),
    C_GREYHOUND("Greyhound", "greyhound", "http://www.shipgreyhound.com/e/pages/Home.aspx"),
    C_8EUROPE("8Europe", "8europe", "http://www.8europe.com"),
    C_FIRSTMILE("FirstMile", "firstmile", "https://track.firstmile.com/"),
    C_OVERSEAS_LOGISTICS("Overseas Logistics", "overseas-logistics", "http://www.overseaslogistics.in/tracking.aspx"),
    C_ROYAL_SHIPMENTS("Royal Shipments", "royal-shipments", "http://royalshipments.com"),
    C_GLOBEGISTICS("Globegistics Inc.", "globegistics", "http://www.globegisticsinc.com/"),
    C_DELLIN("Dellin", "dellin", "https://www.dellin.ru/tracker/"),
    C_CBTSD("Better Express", "cbtsd", "http://www.cbtsd.com/"),
    C_SUYD56("SYD Express", "suyd56", "http://www.suyd56.com/"),
    C_BLUECARE("Bluecare Express", "bluecare", "https://bluecare.express/"),
    C_NEXIVE("Nexive", "nexive", "http://www.sistemacompleto.it/Tracking-Spedizioni-Nexive.aspx"),
    C_TK_KIT("Tk Kit", "tk-kit", "http://tk-kit.ru/"),
    C_ASENDIA_HK("Asendia HK", "asendia-hk", "http://www.asendia.hk/"),
    C_LINEXSOLUTIONS("Linex", "linexsolutions", "http://tracking.linexsolutions.com/"),
    C_INTELCOM("intelcom", "intelcom", "https://intelcomexpress.com/en"),
    C_OVERNITENET("Overnite Express", "overnitenet", "http://www.overnitenet.com/"),
    C_AIRWINGS_INDIA("Airwings Courier Express India", "airwings-india", "http://www.airwingsindia.com/"),
    C_HERMES_DE("Hermes Germany", "hermes-de", "https://www.myhermes.de/wps/portal/paket/Home/privatkunden/home"),
    C_JT_EXPRESS_TH("J&T Express TH", "jt-express-th", ""),
    C_PROFESSIONAL_COURIERS("The Professional Couriers (TPC)", "professional-couriers", "http://www.tpcindia.com/"),
    C_ESNAD("ESNAD Express", "esnad", "https://www.esnadexpress.com/"),
    C_INTERNATIONAL_SEUR("International Seur", "international-seur", "http://www.seur.com/"),
    C_ABF("ABF Freight", "abf", "http://www.abfs.com/"),
    C_ASMRED("ASM", "asmred", "http://en.asmred.com/track-your-shipment/"),
    C_TRAKPAK("TrakPak", "trakpak", "http://www.trackmytrakpak.com/trakpak.aspx"),
    C_XINGYUNYI("XingYunYi", "xingyunyi", "http://wms.xingyunyi.cn/tracking?numbers"),
    C_TNT_LT("TNT LT", "tnt-lt", "http://www.tnt.com"),
    C_MATKAHUOLTO("Matkahuolto", "matkahuolto", "https://www.matkahuolto.fi/fi/"),
    C_MONDIALRELAY("Mondial Relay", "mondialrelay", "https://www.mondialrelay.fr/suivi-de-colis/"),
    C_COURIERS_PLEASE("Couriers Please express", "couriers-please", "http://www.couriersplease.com.au/"),
    C_ACSCOURIER("ACS Courier", "acscourier", "https://www.acscourier.net/el/home"),
    C_BT_EXP("LJS", "bt-exp", "http://www.bt-exp.com/"),
    C_DHL_FR("dhl-fr", "dhl-fr", "https://www.dhl.com/fr-fr/home.html"),
    C_RL_CARRIERS("RL Carriers", "rl-carriers", "http://www.rlcarriers.com/"),
    C_AFGHAN_POST("Afghan Post", "afghan-post", "http://afghanpost.gov.af/"),
    C_DPD_POLAND("DPD Poland", "dpd-poland", "https://www.dpd.com.pl/"),
    C_ASIAFLY("AsiaFly", "asiafly", "http://www.asiafly.com.cn/"),
    C_GLS_PL("gls-pl", "gls-pl", "https://gls-group.eu/PL/pl/home"),
    C_POSTA_SHQIPTARE("Albania Post", "posta-shqiptare", "http://www.postashqiptare.al/"),
    C_TAXYDROMIKI("Geniki Taxydromiki", "taxydromiki", "http://www.taxydromiki.gr/"),
    C_CESS("Cess", "cess", "http://www.gto365.com/"),
    C_HANJIN("Hanjin Shipping", "hanjin", "http://www.hanjin.co.kr/"),
    C_POSTAPLUS("PostaPlus", "postaplus", "https://www.postaplus.com/"),
    C_ANDORRA_POST("Andorra Post", "andorra-post", "http://www.laposte.fr/"),
    C_ENVIALIA("Envialia", "envialia", "http://www.envialia.com/"),
    C_BESTEX("Best Express", "bestex", "http://www.800bestex.com/"),
    C_1SHIDA("1SD", "1shida", ""),
    C_CANPAR("Canpar Courier", "canpar", "http://www.canpar.ca/en/home.jsp"),
    C_ADICIONAL("Adicional Logistics", "adicional", "http://www.adicional.pt/"),
    C_NJFEIBAO("Flying Leopards Express", "njfeibao", "http://njfeibao.com"),
    C_17POSTSERVICE("17 Post Service", "17postservice", "http://17postservice.com/"),
    C_CBL_LOGISTICA("CBL Logistics", "cbl-logistica", "http://www.cbl-logistica.com/"),
    C_FIRSTFLIGHTME("First Flight Couriers", "firstflightme", "http://firstflightme.com/Track-Shipment"),
    C_VNCPOST("VNCPost", "vncpost", "https://vncpost.com"),
    C_JET("JET", "jet", "http://www.jet.co.id"),
    C_REDUR_ES("Redur Spain", "redur-es", "http://www.redur.es/"),
    C_ANTILLES_POST("Antilles Post", "antilles-post", "http://www.cpostinternational.com/"),
    C_CORREO_ARGENTINO("Argentina Post", "correo-argentino", "http://www.correoargentino.com.ar/"),
    C_SIODEMKA("Siodemka", "siodemka", "https://www.siodemka.com/"),
    C_360LION("360lion Express", "360lion", "http://www.360lion.com"),
    C_ZTO_INTERNATIONAL("ZTO International", "zto-international", "https://www.ztoglobal.com/"),
    C_ARMENIA_POST("Armenia Post", "armenia-post", "http://www.haypost.am/"),
    C_ARUBA_POST("Aruba Post", "aruba-post", "http://www.postaruba.com/"),
    C_EXAPAQ("DPD France", "exapaq", "http://www.dpd.fr/"),
    C_HCT("HCT Express", "hct", "https://www.hct.com.tw/Default.aspx"),
    C_LDXPRESS("LDXpress", "ldxpress", "http://www.ldxpress.com/"),
    C_SPRING_GDS("spring-gds", "spring-gds", "https://www.spring-gds.com"),
    C_AUSTRIA_POST("Austrian Post", "austria-post", "http://www.post.at/"),
    C_AZERBAIJAN_POST("Azerbaijan Post", "azerbaijan-post", "http://www.azerpost.az/"),
    C_DOORTODOOR("CJ Logistics", "doortodoor", "https://www.doortodoor.co.kr/parcel/pa_004.jsp"),
    C_TCS_EXPRESS("tcs-express", "tcs-express", "https://www.tcsexpress.com"),
    C_BAHRAIN_POST("Bahrain Post", "bahrain-post", "http://www.bahrain.bh/"),
    C_KUAJINGYIHAO("K1 Express", "kuajingyihao", "http://www.kuajingyihao.com/"),
    C_VOVA_LOGISTICS("VOVA Logistics", "vova-logistics", "https://www.vovalogistics.com/index.php?q=admin/main/index/"),
    C_JT_EXPRESS("JT Express", "jt-express", "https://jtexpress.vn/en/home.html"),
    C_BANGLADESH_EMS("Bangladesh EMS", "bangladesh-ems", "http://www.bangladeshpost.gov.bd/"),
    C_QI_ELEVEN("7-ELEVEN", "qi-eleven", "https://eservice.7-11.com.tw/E-Tracking/search.aspx"),
    C_BARBADOS_POST("Barbados Post", "barbados-post", "http://www.bps.gov.bb/"),
    C_BELPOCHTA("Belarus Post", "belpochta", "http://belpost.by/"),
    C_ORANGECONNEX("ORANGE CONNEX", "orangeconnex", "http://www.orangeconnex.com.cn"),
    C_CTT_EXPRESS("CTT Express", "ctt-express", "https://www.cttexpress.com"),
    C_BELIZE_POST("Belize Post", "belize-post", "http://www.belizepostalservice.gov.bz"),
    C_007EX("007EX", "007ex", "http://www.007ex.ru"),
    C_BENIN_POST("Benin Post", "benin-post", "http://www.laposte.bj/"),
    C_GLS_NL("GLS Netherland", "gls-nl", "https://www.gls-info.nl"),
    C_BERMUDA_POST("Bermuda Post", "bermuda-post", "http://www.bpo.bm/"),
    C_JS_EXP("JS EXPRESS", "js-exp", "http://www.js-exp.com"),
    C_WEWORLD_EXPRESS("We World Express", "weworld-express", "https://www.weworldexpress.com/wwe/track"),
    C_BHUTAN_POST("Bhutan Post", "bhutan-post", "http://www.bhutanpost.bt/"),
    C_CORREOS_BOLIVIA("Bolivia Post", "correos-bolivia", "http://www.correosbolivia.com/"),
    C_GOFLY("Gofly", "gofly", "http://goflyi.com/"),
    C_BOSNIA_AND_HERZEGOVINA_POST("Bosnia And Herzegovina Post", "bosnia-and-herzegovina-post", "http://www.posta.ba/"),
    C_GAOPOST("Gao Post", "gaopost", "http://www.gaopost.com/"),
    C_SPX_VN("Shopee Express VN", "spx-vn", "https://spx.vn"),
    C_BOTSWANA_POST("Botswana Post", "botswana-post", "http://www.botspost.co.bw/"),
    C_SPX_MY("Shopee Express MY", "spx-my", "https://shopeexpress.com.my"),
    C_BRUNEI_POST("Brunei Post", "brunei-post", "http://www.post.gov.bn/"),
    C_DBSCHENKER("DB Schenker", "dbschenker", "https://www.dbschenker.com/"),
    C_BULGARIA_POST("Bulgaria Post", "bulgaria-post", "http://www.bgpost.bg/"),
    C_JDY("JINDOUYUN Logistics", "jdy", "http://www.szjdy.ltd/"),
    C_SONAPOST("Burkina Faso Post", "sonapost", "http://www.sonapost.bf/"),
    C_UKMAIL("UK Mail", "ukmail", "https://www.ukmail.com"),
    C_BURUNDI_POST("Burundi Post", "burundi-post", "http://www.poste.bi/indexen.htm"),
    C_SINOAIR("SINOAIR", "sinoair", "http://www.sinoair.com/index.php"),
    C_ZHONGSU("ZHONGSU International", "zhongsu", "http://zsgjky.com/"),
    C_CAMBODIA_POST("Cambodia Post", "cambodia-post", "http://www.cambodiapost.com.kh/"),
    C_DETRACK("Detrack", "detrack", "https://www.detrack.com"),
    C_UKTRACKING_ASENDIA("UK Asendia", "uktracking-asendia", "https://uktracking.asendia.com"),
    C_CAMPOST("Cameroon Post", "campost", "http://www.campost.cm/"),
    C_ITALY_SDA("Italy SDA", "italy-sda", "http://www.sda.it/"),
    C_ASENDIA_WMP("Asendia UK Premium", "asendia-wmp", "https://watchmyparcel.com/asendia"),
    C_CORREIOS_CABO_VERDE("Correios Cabo Verde", "correios-cabo-verde", "http://www.correios.cv/"),
    C_PALLETWAYS("Palletways", "palletways", "https://www.palletwaysonline.com"),
    C_T_CAT("T Cat", "t-cat", "http://www.t-cat.com.tw/"),
    C_YHT("Eshipping", "yht", "http://www.eshippinggateway.com"),
    C_JT_EXPRESS_PH("JT Express PH", "jt-express-ph", "https://www.jtexpress.ph/index/query/gzquery.html"),
    C_FASTWAY_ZA("Fastway South Africa", "fastway-za", "http://www.fastway.co.za/our-services/track-your-parcel"),
    C_FASTGO("Fastgo", "fastgo", "http://www.fastgo.com.au/"),
    C_COLOMBIA_POST("Colombia Post", "colombia-post", "http://www.4-72.com.co/"),
    C_DELCART_IN("Delcart", "delcart-in", "http://www.delcart.in/"),
    C_WEASHIP("Weaship", "weaship", "http://www.weaship.com.cn/"),
    C_PCA("PCA", "pca", "http://www.pcaexpress.com.au"),
    C_FULFILLMEN("Fulfillmen", "fulfillmen", "https://www.fulfillmen.com/"),
    C_GTI("GTI", "gti", "http://www.gti56.com/"),
    C_CITYLINKEXPRESS("City-Link Express", "citylinkexpress", "http://www.citylinkexpress.com/"),
    C_FTD("FTD Express", "ftd", "http://www.ftd.nz/"),
    C_TUFFNELLS("tuffnells", "tuffnells", "https://www.tuffnells.co.uk/track-and-trace"),
    C_2GO("2GO", "2go", "http://supplychain.2go.com.ph/"),
    C_PFLOGISTICS("Parcel Freight Logistics", "pflogistics", "http://www.pflogistics.com.au/"),
    C_SHIPGCE("Shipgce Express", "shipgce", "http://www.shipgce.com"),
    C_FREAKYQUICK("freaky quick logistics", "freakyquick", "http://www.freakyquick.com.au/"),
    C_TURTLE_EXPRESS("Turtle express", "turtle-express", "http://turtle-express.net/index.html"),
    C_HRVATSKA_POSTA("Croatia Post", "hrvatska-posta", "http://www.posta.hr/"),
    C_XEND("Xend Express", "xend", "http://new.xend.com.ph/"),
    C_EXELOT("Exelot", "exelot", "https://my.exelot.com/public/track/"),
    C_CUBA_POST("Cuba Post", "cuba-post", "http://www.correos.cu/rastreador-de-envios/"),
    C_WISE_EXPRESS("Wise Express", "wise-express", "http://www.shwise.cn/"),
    C_SURE56("Sure56", "sure56", "http://www.sure56.com"),
    C_CEVA_LOGISTICS("CEVA Logistics", "ceva-logistics", "https://www.cevalogistics.com"),
    C_CYPRUS_POST("Cyprus Post", "cyprus-post", "http://www.mcw.gov.cy/"),
    C_AIR21("AIR21", "air21", "http://www.air21.com.ph/"),
    C_GATICN("GATI Courier", "gaticn", "http://www.gati.com/"),
    C_CNPEX("Cnpex", "cnpex", "http://www.cnpex.com.au/"),
    C_UBX_UK("UBX Express", "ubx-uk", "https://www.ubx.uk.net"),
    C_JTEXPRESS("JT Express", "jtexpress", "http://www.jtexpress.com.cn/"),
    C_DENMARK_POST("Denmark post", "denmark-post", "http://www.postdanmark.dk/"),
    C_AIRSPEED("Airspeed International Corporation", "airspeed", "http://www.airspeed.com.ph/"),
    C_SZDPEX("DPEX China", "szdpex", "http://www.szdpex.com.cn"),
    C_1HCANG("1hcang", "1hcang", "http://www.1hcang.com/"),
    C_SHREE_MAHABALI_EXPRESS("Shree Mahabali Express", "shree-mahabali-express", "http://www.shreemahabaliexpress.com/"),
    C_SAILPOST("Sailpost", "sailpost", "https://www.sailpost.it/traccia-il-pacco/"),
    C_RAF("RAF Philippines", "raf", "http://www.raf.ph/"),
    C_ASYAD("Asyad Express", "asyad", "https://asyadexpress.com/track-your-order/"),
    C_INPOSDOM("Dominican Post", "inposdom", "http://www.inposdom.gob.do/"),
    C_TEA_POST("Tea post", "tea-post", "http://www.tea-post.com"),
    C_YDHEX("YDH", "ydhex", "http://www.ydhex.com"),
    C_TIKI("Tiki", "tiki", "https://tiki.id/id/home"),
    C_CORREOS_DEL_ECUADOR("Ecuador Post", "correos-del-ecuador", "http://www.correosdelecuador.gob.ec/"),
    C_SUNYOU("Sunyou", "sunyou", "http://www.sunyou.hk/"),
    C_QUICKWAY("QuicKway", "quickway", "http://www.quickway-sc.com/"),
    C_EGYPT_POST("Egypt Post", "egypt-post", "http://www.egyptpost.org/"),
    C_WAHANA("Wahana", "wahana", "http://wahana.com/"),
    C_EL_SALVADOR_POST("El Salvador Post", "el-salvador-post", "http://www.correos.gob.sv/"),
    C_DHLECOMMERCE_ASIA("DHL Global Mail Asia", "dhlecommerce-asia", "https://dhlecommerce.asia/Portal/Track"),
    C_GHN("Giao Hàng Nhanh", "ghn", "https://ghn.vn"),
    C_ERITREA_POST("Eritrea Post", "eritrea-post", "http://www.eriposta.com/"),
    C_DHL_ACTIVE("DHL Active Tracing", "dhl-active", "https://activetracing.dhl.com/DatPublic/datSelection.do"),
    C_OMNIVA("Estonia Post", "omniva", "https://www.omniva.ee/"),
    C_VIETTELPOST("Viettel Post", "viettelpost", "http://en.viettelpost.com.vn/"),
    C_ETHIOPIA_POST("Ethiopia Post", "ethiopia-post", "http://www.ethiopostal.com/"),
    C_TNT_REFERENCE("TNT Reference", "tnt-reference", "http://www.tnt.com/webtracker/tracker.do?navigation=1&respLang=en"),
    C_YUNLU("YL express", "yunlu", "http://www.yl-scm.com/"),
    C_FAROE_ISLANDS_POST("Faroe Islands Post", "faroe-islands-post", "http://www.posta.fo/"),
    C_DOTZOT("Dotzot", "dotzot", "http://dotzot.in/index-web.html"),
    C_FIJI_POST("Fiji Post", "fiji-post", "http://www.postfiji.com.fj/"),
    C_KANGAROO_MY("Kangaroo Worldwide Express", "kangaroo-my", "http://www.kangaroo.com.my/"),
    C_FINLAND_POSTI("Finland Post - Posti", "finland-posti", "http://www.posti.fi/"),
    C_JIAYI56("Jiayi Express", "jiayi56", "http://www.jiayi56.com/"),
    C_KERRYEXPRESS("Kerry Express", "kerryexpress", "https://kerryexpress.com.vn"),
    C_DELTEC_COURIER("Deltec Courier", "deltec-courier", "https://www.deltec-courier.com/"),
    C_GEL_EXPRESS("GEL Express", "gel-express", "https://gel-express.de/"),
    C_MAXCELLENTS("Maxcellents Pte Ltd", "maxcellents", "http://www.maxcellents.com.sg/"),
    C_NATIONWIDE_MY("Nationwide Express", "nationwide-my", "http://www.nationwide2u.com/"),
    C_BUFFALOEX("Buffalo", "buffaloex", "http://www.buffaloex.com/index.html"),
    C_GEORGIAN_POST("Georgia Post", "georgian-post", "http://www.gpost.ge/"),
    C_RPXONLINE("RPX Online", "rpxonline", "http://www.rpxonline.com/"),
    C_SCOREJP("Score Jp", "scorejp", "http://www.scorejp.com/china/index.html"),
    C_GHANA_POST("Ghana Post", "ghana-post", "http://www.ghanapost.com.gh/"),
    C_GIBRALTAR_POST("Gibraltar  Post", "gibraltar-post", "http://www.post.gi/"),
    C_NHANS_SOLUTIONS("Nhans Solutions", "nhans-solutions", "http://www.nhans.sg/"),
    C_LDLOG("LD Logistics", "ldlog", "http://www.ldlog.com.cn/"),
    C_ESPEEDPOST("Espeedpost", "espeedpost", "http://www.espeedpost.com/"),
    C_TELE_POST("Greenland Post", "tele-post", "http://www.post.gl/"),
    C_JET_SHIP("Jet-Ship Worldwide", "jet-ship", "http://jet-ship.com/"),
    C_XPOST("XPOST", "xpost", "https://www.xpost.ph"),
    C_MYAUSTRIANPOST("GmbH", "myaustrianpost", "https://myaustrianpost.de/"),
    C_ELCORREO("Guatemala Post", "elcorreo", "http://www.elcorreo.com.gt/"),
    C_ECARGO_ASIA("Ecargo", "ecargo-asia", "http://ecargo.asia/"),
    C_GUERNSEY_POST("Guernsey Post", "guernsey-post", "http://www.guernseypost.com/"),
    C_DELHIVERY("Delhivery", "delhivery", "http://www.delhivery.com/"),
    C_COSEX("Cosex", "cosex", "http://www.huihe56.com"),
    C_GLS("GLS", "gls", "https://gls-group.eu/EU/en/home"),
    C_BARTOLINI("BRT Bartolini", "bartolini", "http://www.brt.it"),
    C_NUVOEX("NuvoEx", "nuvoex", "http://www.nuvoex.com/"),
    C_ETS_EXPRESS("ETS Express", "ets-express", "http://www.ets-express.com/"),
    C_HT56("Hong Tai", "ht56", "http://www.ht56.com/index.html"),
    C_DPD("DPD", "dpd", "http://www.dpd.com/"),
    C_PARCELLED_IN("Parcelled.in", "parcelled-in", "http://parcelled.in/"),
    C_ELIANPOST("E-lian", "elianpost", "http://www.elianpost.com/index.html"),
    C_ARAMEX("Aramex", "aramex", "http://www.aramex.com/"),
    C_TOLL("TOLL", "toll", "http://www.tollgroup.com"),
    C_ECOM_EXPRESS("Ecom Express", "ecom-express", "http://www.ecomexpress.in/"),
    C_QUANTIUM("Quantium", "quantium", "http://quantiumsolutions.com/hk-tc/"),
    C_BTD56("Bao Tongda Freight Forwarding", "btd56", "http://www.btdair.com/en/"),
    C_ICELAND_POST("Iceland Post", "iceland-post", "http://www.postur.is/"),
    C_GDEX("GDEX", "gdex", "http://www.gdexpress.com/"),
    C_ALPHA_FAST("Alpha Fast", "alpha-fast", "http://www.alphafast.com/"),
    C_SHREEMARUTICOURIER("Shree Maruti Courier", "shreemaruticourier", "https://www.shreemaruticourier.com/"),
    C_OMNIPARCEL("Omni Parcel", "omniparcel", "http://track.omniparcel.com"),
    C_INDONESIA_POST("Indonesia Post", "indonesia-post", "http://www.posindonesia.co.id/"),
    C_SKYNET("SkyNet Malaysia", "skynet", "http://www.skynet.com.my/"),
    C_CDEK("CDEK Express", "cdek", "https://cdek-express.com/"),
    C_BQC("BQC", "bqc", "http://www.1001000.com"),
    C_IRAN_POST("Iran Post", "iran-post", "http://post.ir/"),
    C_TRACKON("Trackon Courier", "trackon", "http://trackoncourier.com"),
    C_HNFYWL("Hnfywl", "hnfywl", "http://www.hnfywl.com/"),
    C_ISRAEL_POST("Israel Post", "israel-post", "http://www.israelpost.co.il/"),
    C_POSTNL_3S("PostNL International 3S", "postnl-3s", "http://www.postnl.nl/voorthuis/"),
    C_OCSCHINA("OCS Express", "ocschina", "http://www.ocschina.com/"),
    C_KERRY_TEC("Kerry Tec", "kerry-tec", "http://www.kerry-tec.com/"),
    C_IVORY_COAST_EMS("Ivory Coast EMS", "ivory-coast-ems", "http://www.laposte.ci/"),
    C_NAQEL("Naqel", "naqel", "http://www.naqel.com.sa/shipment_tracking.php"),
    C_8256RU("BEL", "8256ru", "http://www.8256ru.com"),
    C_JAMAICA_POST("Jamaica Post", "jamaica-post", "http://www.jamaicapost.gov.jm/"),
    C_PARCEL("Pitney Bowes", "parcel", "https://parceltracking.pb.com/app/"),
    C_CXC("CXC", "cxc", "http://cxc.com.hk"),
    C_JORDAN_POST("Jordan Post", "jordan-post", "http://www.jordanpost.com.jo/"),
    C_ONEWORLDEXPRESS("One World Express", "oneworldexpress", "http://www.oneworldexpress.com/"),
    C_KAZPOST("Kazakhstan Post", "kazpost", "http://www.kazpost.kz/"),
    C_ADSONE("ADSOne", "adsone", "http://tracking.adsone.com.au/"),
    C_BSI("BSI express", "bsi", "http://www.bsiscm.com/"),
    C_AMAZON("Amazon Logistics", "amazon", "https://logistics.amazon.com/"),
    C_KENYA_POST("Kenya Post", "kenya-post", "http://www.posta.co.ke/"),
    C_LANDMARK_GLOBAL("Landmark Global", "landmark-global", "http://landmarkglobal.com/"),
    C_AIRFEX("Airfex", "airfex", "http://www.airfex.net"),
    C_THECOURIERGUY("The Courier Guy", "thecourierguy", "http://www.thecourierguy.co.za/"),
    C_KKE("King Kong Express", "kke", "http://www.szkke.com/index.php"),
    C_SMSA_EXPRESS("SMSA Express", "smsa-express", "http://www.smsaexpress.com/"),
    C_800BEST("Best Express(logistic)", "800best", "http://www.800best.com"),
    C_COSTMETICSNOW("Cosmetics Now", "costmeticsnow", "https://www.cosmeticsnow.com/"),
    C_KYRGYZPOST("Kyrgyzstan Post", "kyrgyzpost", "http://kyrgyzpost.kg/"),
    C_SFCSERVICE("SFC Service", "sfcservice", "http://www.sfcservice.com/"),
    C_LAOS_POST("Laos Post", "laos-post", "http://www.laopostapl.com"),
    C_LATVIJAS_PASTS("Latvia Post", "latvijas-pasts", "http://www.pasts.lv/"),
    C_EC_FIRSTCLASS("EC-Firstclass", "ec-firstclass", "http://www.ec-firstclass.org/"),
    C_YJI("YJI", "yji", "http://www.yanjin-gj.com"),
    C_LIBAN_POST("Lebanon Post", "liban-post", "http://www.libanpost.com/"),
    C_HERMES_UK("MyHermes UK", "hermes-uk", "http://www.myhermes.co.uk/"),
    C_HI_LIFE("Hi Life", "hi-life", "http://www.hilife.com.tw/"),
    C_LESOTHO_POST("Lesotho Post", "lesotho-post", "http://lesothopost.org.ls/"),
    C_DHLGLOBALMAIL("DHL ECommerce", "dhlglobalmail", "http://webtrack.dhlglobalmail.com/"),
    C_WEDO("WeDo Logistics", "wedo", "http://www.wedoexpress.com/en/"),
    C_SPEEDPAK("SpeedPAK", "speedpak", "http://www.orangeconnex.com.cn/"),
    C_DPD_UK("DPD UK", "dpd-uk", "http://www.dpd.co.uk/"),
    C_GEODIS("Geodis", "geodis", "http://www.geodis.com/"),
    C_TNT_UK("TNT UK", "tnt-uk", "www.tnt.co.uk"),
    C_ZAJIL("Zajil", "zajil", "https://zajil-express.com/en/"),
    C_LIECHTENSTEIN_POST("Liechtenstein Post", "liechtenstein-post", "http://www.post.li/"),
    C_LTEXP("Ltexp", "ltexp", "http://www.ltexp.com.cn/"),
    C_LIETUVOS_PASTAS("Lithuania Post", "lietuvos-pastas", "http://www.post.lt/"),
    C_LGS("Lazada (LEX)", "lgs", "https://tracker.lel.asia/"),
    C_CJ_DROPSHIPPING("CJ Packet", "cj-dropshipping", "http://cjpacket.com/"),
    C_LUXEMBOURG_POST("Luxembourg Post", "luxembourg-post", "http://www.post.lu/"),
    C_GLS_ITALY("GLS Italy", "gls-italy", "http://www.gls-italy.com/"),
    C_INPOST_PACZKOMATY("InPost Paczkomaty", "inpost-paczkomaty", "https://paczkomaty.pl"),
    C_JAYEEK("Jayeek", "jayeek", "http://www.jayeek.com/index.html"),
    C_DSV("DSV", "dsv", "http://www.dsv.com/"),
    C_STAR_TRACK("StarTrack", "star-track", "https://startrack.com.au/"),
    C_DEKUN("Dekun", "dekun", "http://www.dekuncn.com"),
    C_17FEIA("17Feia Express", "17feia", "http://www.17feia.com/"),
    C_MACEDONIA_POST("Macedonia Post", "macedonia-post", "http://www.posta.mk/"),
    C_ECHO("Echo", "echo", "http://echo.com/"),
    C_BLUESKYEXPRESS("Blue Sky Express", "blueskyexpress", "http://www.blueskyexpress.com.au/"),
    C_DPD_IRELAND("DPD Ireland", "dpd-ireland", "http://dpd.ie/"),
    C_EMPSEXPRESS("EMPS Express", "empsexpress", "http://www.empsexpress.com/"),
    C_YIMIDIDA("YMDD", "yimidida", "https://www.yimidida.com/home/home.jsp"),
    C_DHL_GLOBAL_LOGISTICS("DHL Global Forwarding", "dhl-global-logistics", "http://www.logistics.dhl/"),
    C_TOLL_IPEC("Toll IPEC", "toll-ipec", "http://www.tollgroup.com/tollipec"),
    C_ONTRAC("OnTrac", "ontrac", "https://www.ontrac.com/index.asp"),
    C_POSLAJU("PosLaju", "poslaju", "http://www.poslaju.com.my/"),
    C_MALAYSIA_POST("Malaysia Post", "malaysia-post", "http://www.pos.com.my/"),
    C_ASENDIA_USA("Asendia USA", "asendia-usa", "http://www.brokersworldwide.com/"),
    C_CPACKET("CPacket", "cpacket", "http://www.canadaposteway.cn/"),
    C_ECPOST("ECPOST", "ecpost", "http://www.ecpostchina.com/"),
    C_APRCHE("Aprche", "aprche", "http://post.aprche.net"),
    C_MALDIVES_POST("Maldives Post", "maldives-post", "http://www.maldivespost.com/"),
    C_ASENDIA_UK("Asendia UK", "asendia-uk", "http://www.asendia.co.uk/"),
    C_CACESAPOSTAL("Cacesa Postal", "cacesapostal", "http://www.cacesapostal.com/"),
    C_TAQBIN_MY("TAQBIN Malaysia", "taqbin-my", "http://my.ta-q-bin.com/"),
    C_YODEL("Yodel", "yodel", "http://www.yodel.co.uk/"),
    C_CRE("CRE", "cre", "http://www.cre.cn/"),
    C_XINGYUAN("Xing Yuan", "xingyuan", "http://new.sz-tianma.com"),
    C_MALTA_POST("Malta Post", "malta-post", "http://www.maltapost.com/"),
    C_ASENDIA_DE("Asendia Germany", "asendia-de", "http://www.asendia.de/en/"),
    C_EKART("Ekart", "ekart", "https://www.ekartlogistics.com/"),
    C_BONDSCOURIERS("Bonds Couriers", "bondscouriers", "http://www.bondscouriers.com.au/"),
    C_FAMIPORT("Famiport", "famiport", "https://www.famiport.com.tw/Web_Famiport/page/process.aspx"),
    C_YMY("Yong Man Yi", "ymy", "http://www.2ezi-ymy.com"),
    C_KERRY_LOGISTICS("Kerry Express", "kerry-logistics", "http://www.kerrylogistics.com/"),
    C_SHREE_TIRUPATI("Shree Tirupati Courier", "shree-tirupati", "http://www.shreetirupaticourier.net/"),
    C_MAURITIUS_POST("Mauritius Post", "mauritius-post", "http://www.mauritiuspost.mu/"),
    C_COURIERPOST("CourierPost", "courierpost", "http://www.courierpost.co.nz/"),
    C_E_CAN("Taiwan Pelican Express", "e-can", "https://www.e-can.com.tw"),
    C_SAFEXPRESS("Safexpress", "safexpress", "http://www.safexpress.com/"),
    C_MEEST("Meest Express", "meest", "https://t.meest-group.com/en"),
    C_MOLDOVA_POST("Moldova Post", "moldova-post", "http://www.posta.md/"),
    C_PUROLATOR("Purolator", "purolator", "http://www.purolator.com/"),
    C_ACOMMERCE("ACOMMERCE", "acommerce", "https://tracking.acommerce.asia/"),
    C_PONY_EXPRESS("Pony Express", "pony-express", "http://www.ponyexpress.ru"),
    C_LA_POSTE_MONACO("Monaco Post", "la-poste-monaco", "http://www.lapostemonaco.mc/"),
    C_IMLB2C("IML Logistics", "imlb2c", "http://www.imlb2c.com/"),
    C_139EXPRESS("139 ECONOMIC Package", "139express", "http://www.139express.com/"),
    C_HIVEWMS("HiveWMS", "hivewms", "http://www.hivewms.com"),
    C_MONACO_EMS("Monaco EMS", "monaco-ems", "http://www.lapostemonaco.mc/"),
    C_BOXC("Boxc Logistics", "boxc", "https://www.boxc.com"),
    C_MONGOL_POST("Mongol Post", "mongol-post", "http://www.mongolpost.mn/"),
    C_UBI_LOGISTICS("UBI Smart Parcel", "ubi-logistics", "http://www.ubismartparcel.com/"),
    C_POSTA_CRNE_GORE("Montenegro Post", "posta-crne-gore", "http://www.postacg.me/"),
    C_FASTWAY_NZ("Fastway New Zealand", "fastway-nz", "https://www.aramex.co.nz"),
    C_LTIAN("Ltian", "ltian", "http://www.ltianexp.com/"),
    C_DPEX("DPEX", "dpex", "https://www.dpex.com/"),
    C_FASTWAY_AU("Fastway Australia", "fastway-au", "http://www.fastway.com.au/"),
    C_DIRECTFREIGHT_AU("Direct Freight", "directfreight-au", "http://www.directfreight.com.au/"),
    C_GLOBAL("Global Order (Cainiao)", "global", "https://global.cainiao.com/"),
    C_FASTWAY_IE("Fastway Ireland", "fastway-ie", "http://www.fastway.ie/"),
    C_SJTSZ("SJTSZ Express", "sjtsz", "http://www.sjtsz.com.cn/"),
    C_MRW_SPAIN("MRW", "mrw-spain", "https://www.mrw.es"),
    C_USKYEXPRESS("Usky", "uskyexpress", "http://www.uskyexpress.com"),
    C_NAMIBIA_POST("Namibia Post", "namibia-post", "http://www.nampost.com.na/"),
    C_COM1EXPRESS("Come One express", "com1express", "http://www.com1express.net/home.html"),
    C_PACKLINK("Packlink", "packlink", "http://www.packlink.es/es/"),
    C_KYE("KUAYUE EXPRESS", "kye", "http://www.ky-express.com/"),
    C_ARKEXPRESS("Ark express", "arkexpress", "http://www.arkexpress.com.au/"),
    C_UPU("UPU", "upu", "http://globaltracktrace.ptc.post/gtt.web/"),
    C_ARROWXL("Arrow XL", "arrowxl", "http://www.arrowxl.co.uk/"),
    C_I_PARCEL("I-parcel", "i-parcel", "https://www.i-parcel.com/"),
    C_COLIS_PRIVE("Colis Privé", "colis-prive", "https://www.colisprive.fr/"),
    C_WINLINK("Winlink logistics", "winlink", "http://www.winlinklogistics.com"),
    C_MD_EXPRESS("MC Express", "md-express", "http://www.mc-express.cn/default.html"),
    C_BLUEDART("Bluedart", "bluedart", "http://www.bluedart.com/"),
    C_LASERSHIP("LaserShip", "lasership", "http://www.lasership.com/"),
    C_KJKD("Fast Express", "kjkd", "http://www.kjkd.com/"),
    C_CHINA_RUSSIA56("China Russia56", "china-russia56", "http://www.china-russia56.com"),
    C_NEW_CALEDONIA_POST("New Caledonia Post", "new-caledonia-post", "http://www.opt.nc/"),
    C_DTDC("DTDC", "dtdc", "http://dtdc.com/"),
    C_DMM_NETWORK("DMM Network", "dmm-network", "http://www.dmmnetwork.it/"),
    C_XPRESSPOST("xpresspost", "xpresspost", "http://www.canadapost.ca/"),
    C_GRANDSLAMEXPRESS("Grand Slam Express", "grandslamexpress", "http://grandslamexpress.in/"),
    C_NICARAGUA_POST("Nicaragua Post", "nicaragua-post", "http://www.correos.gob.ni/"),
    C_GOJAVAS("GoJavas", "gojavas", "http://gojavas.com/"),
    C_FETCHR("Fetchr", "fetchr", "https://fetchr.us/"),
    C_OPEK("FedEx Poland Domestic", "opek", "http://www.fedex.com/pl/"),
    C_XDP_UK("XDP Express", "xdp-uk", "http://www.xdp.co.uk/"),
    C_EFSPOST("EFSPost", "efspost", "http://www.efspost.com/"),
    C_EPACKET("ePacket", "epacket", "http://www.ems.com.cn/english.html"),
    C_LBEXPS("LiBang International Logistics", "lbexps", "http://www.lbexps.com/"),
    C_NIGERIA_POST("Nigeria Post", "nigeria-post", "http://www.nipost.gov.ng/"),
    C_FIRST_FLIGHT("First Flight", "first-flight", "http://www.firstflight.net/"),
    C_LEDII("Ledii", "ledii", "http://ledii.itdida.com/zhanghao/landing.xhtml"),
    C_SKYNETWORLDWIDE("SkyNet Worldwide Express", "skynetworldwide", "http://www.skynetwwe.com/"),
    C_SGT_IT("SGT Corriere Espresso", "sgt-it", "http://sogetras.it/"),
    C_EYOUPOST("Eyou800", "eyoupost", "http://www.eyou800.com/"),
    C_ETOTAL("eTotal", "etotal", "http://www.e-total.com"),
    C_ZHUOZHI("Top Ideal Express", "zhuozhi", "https://www.esdex.com/"),
    C_GATI_KWE("Gati-KWE", "gati-kwe", "http://www.gatikwe.com/"),
    C_IMEXGLOBALSOLUTIONS("IMEX Global Solutions", "imexglobalsolutions", "http://www.imexglobalsolutions.com/"),
    C_OMAN_POST("Oman Post", "oman-post", "http://www.omanpost.om/"),
    C_KGMHUB("KGM Hub", "kgmhub", "http://kgmhub.com/customer/public-tracking"),
    C_EASY_MAIL("Easy Mail", "easy-mail", "http://easy-mail.gr/"),
    C_QXPRESS("Qxpress", "qxpress", "http://www.qxpress.asia/eng/html/"),
    C_IDEXPRESS("IDEX", "idexpress", "http://www.idexpress.com.cn/"),
    C_FD_EXPRESS("FD Express", "fd-express", "http://www.fangdi56.com/"),
    C_DTDC_PLUS("DTDC Plus", "dtdc-plus", "http://dtdc.com/"),
    C_HOUND("hound", "hound", "http://www.hound-express.com/"),
    C_OCS_WORLDWIDE("OCS Worldwide", "ocs-worldwide", "http://www.ocsworldwide.co.uk"),
    C_ROSAN("ROSAN EXPRESS", "rosan", "http://meest.cn/"),
    C_RRDONNELLEY("RR Donnelley", "rrdonnelley", "http://www.internationalservices.rrd.com/"),
    C_WSGD_LOGISTICS("WSGD Logistics", "wsgd-logistics", "http://www.worldshipgd.com/"),
    C_PARCEL_EXPRESS("Parcel Express", "parcel-express", "http://www.parcelexpress.sg/"),
    C_CON_WAY("Con-way Freight", "con-way", "https://www.con-way.com"),
    C_FEDEX_FREIGHT("Fedex Freight", "fedex-freight", "https://www.fedex.com/us/freight/"),
    C_UEQ("UEQ", "ueq", "http://www.ueq.com"),
    C_ESTAFETAUSA("Estafeta USA", "estafetausa", "https://estafetausa.com/"),
    C_NINJAVAN("Ninja Van", "ninjavan", "http://ninjavan.sg/"),
    C_ZES_EXPRESS("ESHUN International Logistics", "zes-express", "http://www.zes-express.com/"),
    C_SREKOREA("SRE Korea", "srekorea", "http://www.srekorea.co.kr/"),
    C_SPEEDEXCOURIER("Speedex Courier", "speedexcourier", "http://www.speedexcourier.com/"),
    C_FEDEX_GROUND("FedEx Ground", "fedex-ground", "http://www.fedex.com"),
    C_SUMXPRESS("Sum Xpress", "sumxpress", "http://www.sumxpress.com"),
    C_ARTLOGEXPRESS("Art Logexpress", "artlogexpress", "http://artlogexpress.com/"),
    C_OVERSEAS_TERRITORY_FR_EMS("Overseas Territory FR EMS", "overseas-territory-fr-ems", "http://www.chronopost.fr/"),
    C_EXPEDITORS("Expeditors", "expeditors", "http://www.expeditors.com/"),
    C_UTEC("utec", "utec", "http://www.utec.info/"),
    C_TAQBIN_JP("Yamato Japan", "taqbin-jp", "http://www.kuronekoyamato.co.jp/en/"),
    C_SPSR("SPSR", "spsr", "http://www.spsr.ru/"),
    C_DHL_HONG_KONG("DHL Hong Kong", "dhl-hong-kong", "http://www.dhl.com.hk/tc.html"),
    C_EPARCEL_KR("eParcel Korea", "eparcel-kr", "http://eparcel.kr"),
    C_DELTAFILLE("Trending Times", "deltafille", "www.trendingtimes.net"),
    C_CHRONOPOST_PORTUGAL("Chronopost Portugal", "chronopost-portugal", "http://chronopost.pt/"),
    C_FLYWAYEX("Flyway Express", "flywayex", "http://www.flywayex.com/"),
    C_JIAJI("CNEX", "jiaji", "http://www.jiaji.com/"),
    C_SAGAWA("Sagawa", "sagawa", "http://www.sagawa-exp.co.jp/"),
    C_UPS_FREIGHT("UPS Freight", "ups-freight", "http://ltl.upsfreight.com"),
    C_SUNING("SUNING", "suning", "http://wuliu.suning.com/slp/home/home.htm"),
    C_DDEXPRESS("DD Express", "ddexpress", "https://dd.express/"),
    C_XPRESSBEES("XpressBees", "xpressbees", "http://www.xpressbees.com/"),
    C_XDEXPRESS("XDEXPRESS", "xdexpress", "http://www.xdexpress.com.au/"),
    C_ABXEXPRESS_MY("ABX Express", "abxexpress-my", "http://www.abxexpress.com.my/"),
    C_COURIER_IT("Courier IT", "courier-it", "http://www.courierit.co.za/"),
    C_UPS_GROUND("UPS Ground", "ups-ground", "http://www.ups.com"),
    C_DPD_DE("DPD Germany", "dpd-de", "https://tracking.dpd.de/status/gb_GB/404"),
    C_DPD_RO("DPD Romania", "dpd-ro", "https://www.dpd.com/ro_en/home/about_dpd/dpd_romania"),
    C_SPECIALISED_FREIGHT("Specialised Freight", "specialised-freight", "http://www.specialisedfreight.co.za/"),
    C_QICHEN("venucia", "qichen", "http://www.qichen.hk/"),
    C_OVERSEAS_TERRITORY_US_POST("Overseas Territory US Post", "overseas-territory-us-post", "http://www.usps.com/"),
    C_MYPOSTONLINE("Mypostonline", "mypostonline", "http://qsm.mypostonline.com.cn/index.php"),
    C_UPS_MI("UPS Mail Innovations", "ups-mi", "http://www.upsmailinnovations.com/"),
    C_UPS_MAIL_INNOVATIONS("UPS Mail Innovations", "ups-mail-innovations", "http://www.upsmailinnovations.com/"),
    C_RRS("RRS Logistics", "rrs", "https://www.rrswl.com"),
    C_PAKISTAN_POST("Pakistan Post", "pakistan-post", "http://www.pakpost.gov.pk/"),
    C_13_TEN("13ten", "13-ten", "http://www.13-ten.com/"),
    C_JAM_EXPRESS("Jam Express", "jam-express", "http://www.myjamexpress.com/"),
    C_DPE_SOUTH_AFRICA("DPE South Africa", "dpe-south-africa", "http://www.dpe.co.za/"),
    C_SAIA_FREIGHT("Saia LTL Freight", "saia-freight", "https://www.saia.com/"),
    C_DAWN_WING("Dawn Wing", "dawn-wing", "http://www.dawnwing.co.za/"),
    C_138SD("138sd", "138sd", "http://www.138sd.net/"),
    C_HXGJ56("Hanxuan international express", "hxgj56", "http://www.hxgj56.com/index.html"),
    C_CORREOS_PANAMA("Panama Post", "correos-panama", "http://www.correospanama.gob.pa/"),
    C_JAYONEXPRESS("Jayon Express (JEX)", "jayonexpress", "http://jayonexpress.com/"),
    C_FASTRAK_SERVICES("Fastrak Services", "fastrak-services", "http://www.fastrak.co.th/"),
    C_FERCAM("FERCAM Logistics & Transport", "fercam", "https://www.fercam.com/de/home-1.html"),
    C_POSTPNG("Papua New Guinea Post", "postpng", "http://www.postpng.com.pg/"),
    C_NOVA_POSHTA("Nova Poshta", "nova-poshta", "http://novaposhta.ua/"),
    C_KWT56("KWT Express", "kwt56", "http://www.kwt56.com/"),
    C_AUSPOST("Auspost", "auspost", "http://auspost.com.au/"),
    C_CORREO_PARAGUAYO("Paraguay Post", "correo-paraguayo", "http://www.correoparaguayo.gov.py/"),
    C_RPX("RPX Indonesia", "rpx", "http://rpx.co.id/"),
    C_168EXPRESS("Antron Express", "168express", "http://123.58.5.229:8080/home.html"),
    C_SERPOST("Serpost", "serpost", "http://www.serpost.com.pe/"),
    C_PHLPOST("Philippines Post", "phlpost", "http://www.phlpost.gov.ph/"),
    C_SGTWL("SGT Express", "sgtwl", "http://www.sgtwl.cn/"),
    C_CORREOSEXPRESS("correosexpress", "correosexpress", "https://www.correosexpress.com"),
    C_POCZTA_POLSKA("Poland Post", "poczta-polska", "http://www.poczta-polska.pl/"),
    C_FBB("FAST BEE", "fbb", "http://www.xffbb.com"),
    C_WISELOADS("Wiseloads", "wiseloads", "http://wiseloads.com/home.php"),
    C_COE("COE", "coe", "http://www.coe.com.hk/lang?lang=us"),
    C_UC_EXPRESS("UC Express", "uc-express", "http://www.uc56.com/"),
    C_WNDIRECT("wnDirect", "wndirect", "http://wndirect.com/en"),
    C_ELTA_COURIER_GR("ELTA Courier", "elta-courier-gr", "http://www.elta-courier.gr/"),
    C_IPOSITA_RWANDA("Rwanda Post", "iposita-rwanda", "http://www.i-posita.rw/"),
    C_EURODIS("Eurodis", "eurodis", "http://eurodis.com/"),
    C_TIP_SA("TIPSA", "tip-sa", "http://www.tip-sa.com/"),
    C_SAINT_LUCIA_POST("Saint Lucia Post", "saint-lucia-post", "http://www.stluciapostal.com/"),
    C_MATDESPATCH("Matdespatch", "matdespatch", "https://matdespatch.com/my/"),
    C_LHTEX("LHT Express", "lhtex", "http://www.lhtex.com.cn/index.asp"),
    C_SVGPOST("Saint Vincent And The Grenadines", "svgpost", "http://www.svgpost.gov.vc/"),
    C_SAMOA_POST("Samoa Post", "samoa-post", "http://samoapost.ws/"),
    C_TNT_AU("TNT Australia", "tnt-au", "https://www.tnt.com/express/en_au/site/home.html"),
    C_WANBEXPRESS("Wanb Express", "wanbexpress", "http://www.wanbexpress.com/"),
    C_ANSERX("AnserX", "anserx", "http://www.anserx.com/"),
    C_SAN_MARINO_POST("San Marino Post", "san-marino-post", "https://www.poste.sm/on-line/home.html"),
    C_SPRINTPACK("SprintPack", "sprintpack", "http://track.sprintpack.com.cn/"),
    C_KJY("KJY Logistics", "kjy", "http://tracking.kjy.com"),
    C_YAKIT("yakit", "yakit", "https://www.yakit.com/"),
    C_CHOICE("CHOICE Logistics", "choice", "http://en.choicexp.com/"),
    C_SAUDI_POST("Saudi Post", "saudi-post", "http://www.sp.com.sa/"),
    C_KAWA("Kawa", "kawa", "http://kawa.cn/"),
    C_JD_LOGISTICS("JD Logistics", "jd-logistics", "http://www.jdwl.com"),
    C_SENEGAL_POST("Senegal Post", "senegal-post", "http://www.laposte.sn/"),
    C_SERBIA_POST("Serbia Post", "serbia-post", "http://www.posta.rs/"),
    C_TAQBIN_HK("TAQBIN Hong Kong", "taqbin-hk", "http://hk.ta-q-bin.com/tc/"),
    C_LINE_CLEAR("Line Clear Express & Logistics", "line-clear", "https://lineclearexpress.com/my/tracking-mobile/"),
    C_SEYCHELLES_POST("Seychelles Post", "seychelles-post", "http://www.seychellespost.gov.sc/"),
    C_SPEED_POST("Speed Post", "speed-post", "http://www.indiapost.gov.in/"),
    C_UBONEX("UBon Express", "ubonex", "http://www.ubonex.com"),
    C_EUASIA("Euasia Express", "euasia", "http://www.euasia.eu"),
    C_OCA_AR("OCA Argentina", "oca-ar", "http://www.oca.com.ar"),
    C_8DT("Profit Fields", "8dt", "http://www.kuaidi.hk/"),
    C_ASENDIA("Asendia", "asendia", "https://tracking.asendia.com"),
    C_SLOVAKIA_POST("Slovakia Post", "slovakia-post", "http://www.posta.sk/"),
    C_SLOVENIA_POST("Slovenia Post", "slovenia-post", "http://www.posta.si/"),
    C_2UEX("2U Express", "2uex", "http://www.2uex.com/"),
    C_IEPOST("IEPost", "iepost", "http://www.ie-post.com/"),
    C_ESPOST("Espost", "espost", "http://www.espost.es/track"),
    C_SOLOMON_POST("Solomon Post", "solomon-post", "http://www.solomonpost.com.sb/"),
    C_ANE66("Ane Express", "ane66", "http://www.ane56.com"),
    C_ALLJOY("Alljoy", "alljoy", "http://www.alljoylogistics.com/"),
    C_GLOBAL_ROUTERS("Echindia", "global-routers", "http://www.globalrouters.cn/"),
    C_HUIDAEX("Huida Express", "huidaex", "http://huidaex.com/"),
    C_APLUS100("A PLUS EXPRESS", "aplus100", "http://en.aplus100.com/Home/");

    @Getter
    private String name;

    @Getter
    private String code;

    @Getter
    private String url;

    CarrierEnum(String name, String code, String url) {
        this.name = name;
        this.code = code;
        this.url = url;
    }
}
