/**
 * Suppliers action types
 * */


// FETCH ALL CARRIES
export const DO_FETCH_ALL_CARRIES = 'DO_FETCH_ALL_CARRIES';
export const FETCH_ALL_CARRIES_SUCCESS = 'FETCH_ALL_CARRIES_SUCCESS';
export const FETCH_ALL_CARRIES_ERROR = 'FETCH_ALL_CARRIES_ERROR';

// FETCH ALL NO PAGING
export const DO_FETCH_ALL_CARRIERS_NO_PAGING = 'DO_FETCH_ALL_CARRIERS_NO_PAGING';
export const FETCH_ALL_CARRIERS_NO_PAGING_SUCCESS = 'FETCH_ALL_CARRIERS_NO_PAGING_SUCCESS';
export const FETCH_ALL_CARRIERS_NO_PAGING_ERROR = 'FETCH_ALL_CARRIERS_NO_PAGING_ERROR';

// CREATE CARRIE
export const DO_CREATE_CARRIE = 'DO_CREATE_CARRIE';
export const CREATE_CARRIE_SUCCESS = 'CREATE_CARRIE_SUCCESS';
export const CREATE_CARRIE_ERROR = 'CREATE_CARRIE_ERROR';

// UPDATE CARRIE
export const DO_EDIT_CARRIE = 'DO_EDIT_CARRIE';
export const EDIT_CARRIE_SUCCESS = 'EDIT_CARRIE_SUCCESS';
export const EDIT_CARRIE_ERROR = 'EDIT_CARRIE_ERROR';


// DELETE CARRIE
export const DO_DELETE_CARRIE = 'DO_DELETE_CARRIE';
export const DELETE_CARRIE_SUCCESS = 'DELETE_CARRIE_SUCCESS';
export const DELETE_CARRIE_ERROR = 'DELETE_CARRIE_ERROR';

// ACTIVE / DEACTIVATE CARRIE
export const DO_HANDLE_CARRIE = 'DO_HANDLE_CARRIE';
export const HANDLE_CARRIE_SUCCESS = 'HANDLE_CARRIE_SUCCESS';
export const HANDLE_CARRIE_ERROR = 'HANDLE_CARRIE_ERROR';

