/**
 * SellerLevels action types
 * */


// FETCH ALL CATEGORIES
export const DO_FETCH_ALL_CATEGORIES = 'DO_FETCH_ALL_CATEGORIES';
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS';
export const FETCH_ALL_CATEGORIES_ERROR = 'FETCH_ALL_CATEGORIES_ERROR';

// FETCH ALL NO PAGING
export const DO_FETCH_ALL_CATEGORIES_NO_PAGING = 'DO_FETCH_ALL_CATEGORIES_NO_PAGING';
export const FETCH_ALL_CATEGORIES_NO_PAGING_SUCCESS = 'FETCH_ALL_CATEGORIES_NO_PAGING_SUCCESS';
export const FETCH_ALL_CATEGORIES_NO_PAGING_ERROR = 'FETCH_ALL_CATEGORIES_NO_PAGING_ERROR';

// CREATE CATEGORY
export const DO_CREATE_CATEGORY = 'DO_CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';

// UPDATE CATEGORY
export const DO_EDIT_CATEGORY = 'DO_EDIT_CATEGORY';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_ERROR = 'EDIT_CATEGORY_ERROR';


// DELETE CATEGORY
export const DO_DELETE_CATEGORY = 'DO_DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';



