// FETCH ALL CONTENT SETTING
export const DO_FETCH_ALL_CONTENT_SETTING = 'DO_FETCH_ALL_CONTENT_SETTING';
export const FETCH_ALL_CONTENT_SETTING_SUCCESS = 'FETCH_ALL_CONTENT_SETTING_SUCCESS';
export const FETCH_ALL_CONTENT_SETTING_ERROR = 'FETCH_ALL_CONTENT_SETTING_ERROR';

// UPDATE  CONTENT SETTING
export const DO_EDIT_CONTENT_SETTING = 'DO_EDIT_CONTENT_SETTING';
export const EDIT_CONTENT_SETTING_SUCCESS = 'EDIT_CONTENT_SETTING_SUCCESS';
export const EDIT_CONTENT_SETTING_ERROR = 'EDIT_CONTENT_SETTING_ERROR';