// fetch list
export const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS';
export const FETCH_ALL_ORDERS_SUCCESS = 'FETCH_ALL_ORDERS_SUCCESS';
export const FETCH_ALL_ORDERS_ERROR = 'FETCH_ALL_ORDERS_ERROR';

// accept 
export const ACCEPT_CANCEL = 'ACCEPT_CANCEL';
export const ACCEPT_CANCEL_SUCCESS = 'ACCEPT_CANCEL_SUCCESS';
export const ACCEPT_CANCEL_ERROR = 'ACCEPT_CANCEL_ERROR';

// not accept
export const REJECT_CANCEL = 'REJECT_CANCEL';
export const REJECT_CANCEL_SUCCESS = 'REJECT_CANCEL_SUCCESS';
export const REJECT_CANCEL_ERROR = 'REJECT_CANCEL_ERROR';

// not accept
export const SAVE_IMAGE_DESIGN = 'SAVE_IMAGE_DESIGN';
export const SAVE_IMAGE_DESIGN_SUCCESS = 'SAVE_IMAGE_DESIGN_SUCCESS';
export const SAVE_IMAGE_DESIGN_ERROR = 'SAVE_IMAGE_DESIGN_ERROR';

// export order
export const EXPORT_ORDER = 'EXPORT_ORDER';
export const EXPORT_ORDER_SUCCESS = 'EXPORT_ORDER_SUCCESS';
export const EXPORT_ORDER_ERROR = 'EXPORT_ORDER_ERROR';

// import order
export const IMPORT_ORDER = 'IMPORT_ORDER';
export const IMPORT_ORDER_SUCCESS = 'IMPORT_ORDER_SUCCESS';
export const IMPORT_ORDER_ERROR = 'IMPORT_ORDER_ERROR';

// get one order
export const FETCH_ONE_ORDERS = 'FETCH_ONE_ORDERS';
export const FETCH_ONE_ORDERS_SUCCESS = 'FETCH_ONE_ORDERS_SUCCESS';
export const FETCH_ONE_ORDERS_ERROR = 'FETCH_ONE_ORDERS_ERROR';

// edit note
export const EDIT_NOTE = 'EDIT_NOTE';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_ERROR = 'EDIT_NOTE_ERROR';

// edit shipping
export const EDIT_SHIPPING = 'EDIT_SHIPPING';
export const EDIT_SHIPPING_SUCCESS = 'EDIT_SHIPPING_SUCCESS';
export const EDIT_SHIPPING_ERROR = 'EDIT_SHIPPING_ERROR';

// fetch one user

export const FETCH_ONE_USER = 'FETCH_ONE_USER';
export const FETCH_ONE_USER_SUCCESS = 'FETCH_ONE_USER_SUCCESS';
export const FETCH_ONE_USER_ERROR = 'FETCH_ONE_USER_ERROR';

// resolve
export const RESOLVE = 'RESOLVE';
export const RESOLVE_SUCCESS = 'RESOLVE_SUCCESS';
export const RESOLVE_ERROR = 'RESOLVE_ERROR';

export const SET_ACTION_REQUIRED = 'SET_ACTION_REQUIRED';
export const SET_ACTION_REQUIRED_SUCCESS = 'SET_ACTION_REQUIRED_SUCCESS';
export const SET_ACTION_REQUIRED_ERROR = 'SET_ACTION_REQUIRED_ERROR'

export const RESOLVE_ON_HOLD = 'RESOLVE_ON_HOLD';
export const RESOLVE_ON_HOLD_SUCCESS = 'RESOLVE_ON_HOLD_SUCCESS';
export const RESOLVE_ON_HOLD_ERROR = 'RESOLVE_ON_HOLD_ERROR';

export const GET_ALL_SUPPLIER = 'GET_ALL_SUPPLIER';
export const GET_ALL_SUPPLIER_SUCCESS = 'GET_ALL_SUPPLIER_SUCCESS';
export const GET_ALL_SUPPLIER_ERROR = 'GET_ALL_SUPPLIER_ERROR';

export const REFUND = 'REFUND';
export const REFUND_SUCCESS = 'REFUND_SUCCESS';
export const REFUND_ERROR = 'REFUND_ERROR';

export const RESEND = 'RESEND';
export const RESEND_SUCCESS = 'RESEND_SUCCESS';
export const RESEND_ERROR = 'RESEND_ERROR';

export const CANCEL = 'CANCEL';
export const CANCEL_SUCCESS = 'CANCEL_SUCCESS';
export const CANCEL_ERROR = 'CANCEL_ERROR';

export const ASSIGN_SUPPLIER = 'ASSIGN_SUPPLIER';
export const ASSIGN_SUPPLIER_SUCCESS = 'ASSIGN_SUPPLIER_SUCCESS';
export const ASSIGN_SUPPLIER_ERROR = 'ASSIGN_SUPPLIER_ERROR';

export const ASSIGN_CARRIER = 'ASSIGN_CARRIER';
export const ASSIGN_CARRIER_SUCCESS = 'ASSIGN_CARRIER_SUCCESS';
export const ASSIGN_CARRIER_ERROR = 'ASSIGN_CARRIER_ERROR';

export const FETCH_STATISTIC = 'FETCH_STATISTIC';
export const FETCH_STATISTIC_SUCCESS = 'FETCH_STATISTIC_SUCCESS';
export const FETCH_STATISTIC_ERROR = 'FETCH_STATISTIC_ERROR';

export const FETCH_SUPPLIER_WITH_PRODUCT_TYPE = 'FETCH_SUPPLIER_WITH_PRODUCT_TYPE';
export const FETCH_SUPPLIER_WITH_PRODUCT_TYPE_SUCCESS = 'FETCH_SUPPLIER_WITH_PRODUCT_TYPE_SUCCESS';
export const FETCH_SUPPLIER_WITH_PRODUCT_TYPE_ERROR = 'FETCH_SUPPLIER_WITH_PRODUCT_TYPE_ERROR';

export const ADD_TRACKING_ID = 'ADD_TRACKING_ID';
export const ADD_TRACKING_ID_SUCCESS = 'ADD_TRACKING_ID_SUCCESS';
export const ADD_TRACKING_ID_ERROR = 'ADD_TRACKING_ID_ERROR';

export const EXPORT_ERROR_FILE = 'EXPORT_ERROR_FILE';
export const EXPORT_ERROR_FILE_SUCCESS = 'EXPORT_ERROR_FILE_SUCCESS';
export const EXPORT_ERROR_FILE_ERROR = 'EXPORT_ERROR_FILE_ERROR';

export const FETCH_CARRIER_WITH_PRODUCT_TYPE = 'FETCH_CARRIER_WITH_PRODUCT_TYPE';
export const FETCH_CARRIER_WITH_PRODUCT_TYPE_SUCCESS = 'FETCH_CARRIER_WITH_PRODUCT_TYPE_SUCCESS';
export const FETCH_CARRIER_WITH_PRODUCT_TYPE_ERROR = 'FETCH_CARRIER_WITH_PRODUCT_TYPE_ERROR';