/**
 * Products action types
 * */


// FETCH ALL
export const DO_FETCH_ALL_PRODUCTS = 'DO_FETCH_ALL_PRODUCTS';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_ERROR = 'FETCH_ALL_PRODUCTS_ERROR';

// FETCH ALL PRODUCT TYPE  NO PAGING
export const DO_FETCH_ALL_PRODUCT_TYPE_NO_PAGING = 'DO_FETCH_ALL_PRODUCT_TYPE_NO_PAGING';
export const FETCH_ALL_PRODUCT_TYPE_NO_PAGING_SUCCESS = 'FETCH_ALL_PRODUCT_TYPE_NO_PAGING_SUCCESS';
export const FETCH_ALL_PRODUCT_TYPE_NO_PAGING_ERROR = 'FETCH_ALL_PRODUCT_TYPE_NO_PAGING_ERROR';

// FETCH PRODUCT TYPE BY CATEGORY
export const DO_FETCH_ALL_PRODUCT_TYPE = 'DO_FETCH_ALL_PRODUCT_TYPE';
export const FETCH_ALL_PRODUCT_TYPE_SUCCESS = 'FETCH_ALL_PRODUCT_TYPE_SUCCESS';
export const FETCH_ALL_PRODUCT_TYPE_ERROR = 'FETCH_ALL_PRODUCT_TYPE_ERROR';


// FETCH SHOPIFY COLLECTION
export const DO_FETCH_ALL_SHOPIFY_COLLECTION = 'DO_FETCH_ALL_SHOPIFY_COLLECTION';
export const FETCH_ALL_SHOPIFY_COLLECTION_SUCCESS = 'FETCH_ALL_SHOPIFY_COLLECTION_SUCCESS';
export const FETCH_ALL_SHOPIFY_COLLECTION_ERROR = 'FETCH_ALL_SHOPIFY_COLLECTION_ERROR';

// FETCH ALL SELLER
export const DO_FETCH_ALL_SELLER = 'DO_FETCH_ALL_SELLER';
export const FETCH_ALL_SELLER_SUCCESS = 'FETCH_ALL_SELLER_SUCCESS';
export const FETCH_ALL_SELLER_ERROR = 'FETCH_ALL_SELLER_ERROR';

// CREATE
export const DO_CREATE_PRODUCT = 'DO_CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';

// CREATE SHOPIFY COLLECTION
export const DO_CREATE_SHOPIFY_COLLECTION = 'DO_CREATE_SHOPIFY_COLLECTION';
export const CREATE_SHOPIFY_COLLECTION_SUCCESS = 'CREATE_SHOPIFY_COLLECTION_SUCCESS';
export const CREATE_SHOPIFY_COLLECTION_ERROR = 'CREATE_SHOPIFY_COLLECTION_ERROR';

// EDIT
export const DO_EDIT_PRODUCT = 'DO_EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';

// EDIT
export const DO_EDIT_PRINT_FILES = 'DO_EDIT_PRINT_FILES';
export const EDIT_PRINT_FILES_SUCCESS = 'EDIT_PRINT_FILES_SUCCESS';
export const EDIT_PRINT_FILES_ERROR = 'EDIT_PRINT_FILES_ERROR';

// DELETE
// export const DO_DELETE_PRODUCT = 'DO_DELETE_PRODUCT';
// export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
// export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';


