/**
 * ProductTypes action types
 * */


// FETCH ALL
export const DO_FETCH_ALL_PRODUCT_TYPES = 'DO_FETCH_ALL_PRODUCT_TYPES';
export const FETCH_ALL_PRODUCT_TYPES_SUCCESS = 'FETCH_ALL_PRODUCT_TYPES_SUCCESS';
export const FETCH_ALL_PRODUCT_TYPES_ERROR = 'FETCH_ALL_PRODUCT_TYPES_ERROR';

// // FETCH
// export const DO_FETCH_SITE = 'DO_FETCH_SITE';
// export const FETCH_SITE_SUCCESS = 'FETCH_SITE_SUCCESS';
// export const FETCH_SITE_ERROR = 'FETCH_SITE_ERROR';
//

// CREATE
export const DO_CREATE_PRODUCT_TYPE = 'DO_CREATE_PRODUCT_TYPE';
export const CREATE_PRODUCT_TYPE_SUCCESS = 'CREATE_PRODUCT_TYPE_SUCCESS';
export const CREATE_PRODUCT_TYPE_ERROR = 'CREATE_PRODUCT_TYPE_ERROR';

// EDIT
export const DO_EDIT_PRODUCT_TYPE = 'DO_EDIT_PRODUCT_TYPE';
export const EDIT_PRODUCT_TYPE_SUCCESS = 'EDIT_PRODUCT_TYPE_SUCCESS';
export const EDIT_PRODUCT_TYPE_ERROR = 'EDIT_PRODUCT_TYPE_ERROR';

// DELETE
export const DO_DELETE_PRODUCT_TYPE = 'DO_DELETE_PRODUCT_TYPE';
export const DELETE_PRODUCT_TYPE_SUCCESS = 'DELETE_PRODUCT_TYPE_SUCCESS';
export const DELETE_PRODUCT_TYPE_ERROR = 'DELETE_PRODUCT_TYPE_ERROR';

// FETCH COUNTRY
export const DO_FETCH_ALL_COUNTRIES = 'DO_FETCH_ALL_COUNTRIES';
export const FETCH_ALL_COUNTRIES_SUCCESS = 'FETCH_ALL_COUNTRIES_SUCCESS';
export const FETCH_ALL_COUNTRIES_ERROR = 'FETCH_ALL_COUNTRIES_ERROR';

// ACTIVATE
export const DO_ACTIVATE_PRODUCT_TYPE = 'DO_ACTIVATE_PRODUCT_TYPE';
export const ACTIVATE_PRODUCT_TYPE_SUCCESS = 'ACTIVATE_PRODUCT_TYPE_SUCCESS';
export const ACTIVATE_PRODUCT_TYPE_ERROR = 'ACTIVATE_PRODUCT_TYPE_ERROR';

