/**
 * Seller Levels action types
 * */


// FETCH ALL SELLER LEVELS
export const DO_FETCH_ALL_SELLER_LEVELS = 'DO_FETCH_ALL_SELLER_LEVELS';
export const FETCH_ALL_SELLER_LEVELS_SUCCESS = 'FETCH_ALL_SELLER_LEVELS_SUCCESS';
export const FETCH_ALL_SELLER_LEVELS_ERROR = 'FETCH_ALL_SELLER_LEVELS_ERROR';

// FETCH ALL SELLER LEVELS NO PAGING
export const DO_FETCH_ALL_SELLER_LEVELS_NO_PAGING = 'DO_FETCH_ALL_SELLER_LEVELS_NO_PAGING';
export const FETCH_ALL_SELLER_LEVELS_NO_PAGING_SUCCESS = 'FETCH_ALL_SELLER_LEVELS_NO_PAGING_SUCCESS';
export const FETCH_ALL_SELLER_LEVELS_NO_PAGING_ERROR = 'FETCH_ALL_SELLER_LEVELS_NO_PAGING_ERROR';

// CREATE SELLER LEVEL
export const DO_CREATE_SELLER_LEVEL = 'DO_CREATE_SELLER_LEVEL';
export const CREATE_SELLER_LEVEL_SUCCESS = 'CREATE_SELLER_LEVEL_SUCCESS';
export const CREATE_SELLER_LEVEL_ERROR = 'CREATE_SELLER_LEVEL_ERROR';

// UPDATE SELLER LEVEL
export const DO_EDIT_SELLER_LEVEL = 'DO_EDIT_SELLER_LEVEL';
export const EDIT_SELLER_LEVEL_SUCCESS = 'EDIT_SELLER_LEVEL_SUCCESS';
export const EDIT_SELLER_LEVEL_ERROR = 'EDIT_SELLER_LEVEL_ERROR';


// DELETE SELLER LEVEL
export const DO_DELETE_SELLER_LEVEL = 'DO_DELETE_SELLER_LEVEL';
export const DELETE_SELLER_LEVEL_SUCCESS = 'DELETE_SELLER_LEVEL_SUCCESS';
export const DELETE_SELLER_LEVEL_ERROR = 'DELETE_SELLER_LEVEL_ERROR';



