/**
 * SITES action types
 * */


// FETCH ALL SITES
export const DO_FETCH_ALL_SITES = 'DO_FETCH_ALL_SITES';
export const FETCH_ALL_SITES_SUCCESS = 'FETCH_ALL_SITES_SUCCESS';
export const FETCH_ALL_SITES_ERROR = 'FETCH_ALL_SITES_ERROR';

// FETCH ALL NO PAGING
export const DO_FETCH_ALL_SITES_NO_PAGING = 'DO_FETCH_ALL_SITES_NO_PAGING';
export const FETCH_ALL_SITES_NO_PAGING_SUCCESS = 'FETCH_ALL_SITES_NO_PAGING_SUCCESS';
export const FETCH_ALL_SITES_NO_PAGING_ERROR = 'FETCH_ALL_SITES_NO_PAGING_ERROR';

// // FETCH SITE
// export const DO_FETCH_SITE = 'DO_FETCH_SITE';
// export const FETCH_SITE_SUCCESS = 'FETCH_SITE_SUCCESS';
// export const FETCH_SITE_ERROR = 'FETCH_SITE_ERROR';
//
// // CREATE SITES
// export const DO_CREATE_SITE = 'DO_CREATE_SITE';
// export const CREATE_SITE_SUCCESS = 'CREATE_SITE_SUCCESS';
// export const CREATE_SITE_ERROR = 'CREATE_SITE_ERROR';
//
// // EDIT SITES
// export const DO_EDIT_SITE = 'DO_EDIT_SITE';
// export const EDIT_SITE_SUCCESS = 'EDIT_SITE_SUCCESS';
// export const EDIT_SITE_ERROR = 'EDIT_SITE_ERROR';

// DELETE SITE
export const DO_DELETE_SITE = 'DO_DELETE_SITE';
export const DELETE_SITE_SUCCESS = 'DELETE_SITE_SUCCESS';
export const DELETE_SITE_ERROR = 'DELETE_SITE_ERROR';

// ACTIVATE SITE
export const DO_ACTIVATE_SITE = 'DO_ACTIVATE_SITE';
export const ACTIVATE_SITE_SUCCESS = 'ACTIVATE_SITE_SUCCESS';
export const ACTIVATE_SITE_ERROR = 'ACTIVATE_SITE_ERROR';

