/**
 * SUPPLIERS action types
 * */


// FETCH ALL SUPPLIERS
export const DO_FETCH_ALL_SUPPLIERS = 'DO_FETCH_ALL_SUPPLIERS';
export const FETCH_ALL_SUPPLIERS_SUCCESS = 'FETCH_ALL_SUPPLIERS_SUCCESS';
export const FETCH_ALL_SUPPLIERS_ERROR = 'FETCH_ALL_SUPPLIERS_ERROR';

// FETCH ALL NO PAGING
export const DO_FETCH_ALL_SUPPLIERS_NO_PAGING = 'DO_FETCH_ALL_SUPPLIERS_NO_PAGING';
export const FETCH_ALL_SUPPLIERS_NO_PAGING_SUCCESS = 'FETCH_ALL_SUPPLIERS_NO_PAGING_SUCCESS';
export const FETCH_ALL_SUPPLIERS_NO_PAGING_ERROR = 'FETCH_ALL_SUPPLIERS_NO_PAGING_ERROR';

// // FETCH SUPPLIER
// export const DO_FETCH_SUPPLIER = 'DO_FETCH_SUPPLIER';
// export const FETCH_SUPPLIER_SUCCESS = 'FETCH_SUPPLIER_SUCCESS';
// export const FETCH_SUPPLIER_ERROR = 'FETCH_SUPPLIER_ERROR';
//
// // CREATE SUPPLIERS
// export const DO_CREATE_SUPPLIER = 'DO_CREATE_SUPPLIER';
// export const CREATE_SUPPLIER_SUCCESS = 'CREATE_SUPPLIER_SUCCESS';
// export const CREATE_SUPPLIER_ERROR = 'CREATE_SUPPLIER_ERROR';
//
// // EDIT SUPPLIERS
// export const DO_EDIT_SUPPLIER = 'DO_EDIT_SUPPLIER';
// export const EDIT_SUPPLIER_SUCCESS = 'EDIT_SUPPLIER_SUCCESS';
// export const EDIT_SUPPLIER_ERROR = 'EDIT_SUPPLIER_ERROR';

// DELETE SUPPLIER
export const DO_DELETE_SUPPLIER = 'DO_DELETE_SUPPLIER';
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS';
export const DELETE_SUPPLIER_ERROR = 'DELETE_SUPPLIER_ERROR';

