// fetch list
export const FETCH_ALL_BALANCE = 'FETCH_ALL_BALANCE';
export const FETCH_ALL_BALANCE_SUCCESS = 'FETCH_ALL_BALANCE_SUCCESS';
export const FETCH_ALL_BALANCE_ERROR = 'FETCH_ALL_BALANCE_ERROR';

// fetch supplier balance
export const FETCH_OVERVIEW = 'FETCH_OVERVIEW';
export const FETCH_OVERVIEW_SUCCESS = 'FETCH_OVERVIEW_SUCCESS';
export const FETCH_OVERVIEW_ERROR = 'FETCH_OVERVIEW_ERROR';

export const EXPORT = 'EXPORT';
export const EXPORT_SUCCESS = 'EXPORT_SUCCESS';
export const EXPORT_ERROR = 'EXPORT_ERROR';