// fetch list
export const FETCH_ALL_BALANCE = 'FETCH_ALL_BALANCE';
export const FETCH_ALL_BALANCE_SUCCESS = 'FETCH_ALL_BALANCE_SUCCESS';
export const FETCH_ALL_BALANCE_ERROR = 'FETCH_ALL_BALANCE_ERROR';

// fetch user balance
export const FETCH_USER_BALANCE = 'FETCH_USER_BALANCE';
export const FETCH_USER_BALANCE_SUCCESS = 'FETCH_USER_BALANCE_SUCCESS';
export const FETCH_USER_BALANCE_ERROR = 'FETCH_USER_BALANCE_ERROR';

// approve 
export const APPROVE = 'APPROVE';
export const APPROVE_SUCCESS = 'APPROVE_SUCCESS';
export const APPROVE_ERROR = 'APPROVE_ERROR';

// REJECT
export const REJECT = 'REJECT';
export const REJECT_SUCCESS = 'REJECT_SUCCESS';
export const REJECT_ERROR = 'REJECT_ERROR';

export const CUSTOM_TRANSACTION = 'CUSTOM_TRANSACTION';
export const CUSTOM_TRANSACTION_SUCCESS = 'CUSTOM_TRANSACTION_SUCCESS';
export const CUSTOM_TRANSACTION_ERROR = 'CUSTOM_TRANSACTION_ERROR';

export const EXPORT = 'EXPORT';
export const EXPORT_SUCCESS = 'EXPORT_SUCCESS';
export const EXPORT_ERROR = 'EXPORT_ERROR';