/**
 * USERS action types
 * */


// FETCH ALL USERS
export const DO_FETCH_ALL_USERS = 'DO_FETCH_ALL_USERS';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_ERROR = 'FETCH_ALL_USERS_ERROR';

// CREATE USER
export const DO_CREATE_USER = 'DO_CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

// UPDATE USER
export const DO_EDIT_USER = 'DO_EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';


// DELETE USER
export const DO_DELETE_USER = 'DO_DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

// LOCK USER
export const DO_LOCK_USER = 'DO_LOCK_USER';
export const LOCK_USER_SUCCESS = 'LOCK_USER_SUCCESS';
export const LOCK_USER_ERROR = 'LOCK_USER_ERROR';

// EXPORT
export const DO_EXPORT_USERS = 'DO_EXPORT_USERS';
export const EXPORT_USERS_SUCCESS = 'EXPORT_USERS_SUCCESS';
export const EXPORT_USERS_ERROR = 'EXPORT_USERS_ERROR';

