/**
 * Dashboard action types
 * */

// FETCH URGENT NOTE
export const DO_FETCH_URGENT_NOTE = 'DO_FETCH_URGENT_NOTE';
export const FETCH_URGENT_NOTE_SUCCESS = 'FETCH_URGENT_NOTE_SUCCESS';
export const FETCH_URGENT_NOTE_ERROR = 'FETCH_URGENT_NOTE_ERROR';
