// fetch list
export const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS';
export const FETCH_ALL_ORDERS_SUCCESS = 'FETCH_ALL_ORDERS_SUCCESS';
export const FETCH_ALL_ORDERS_ERROR = 'FETCH_ALL_ORDERS_ERROR';

// accept 
export const ACCEPT_ORDERS = 'ACCEPT_ORDERS';
export const ACCEPT_ORDERS_SUCCESS = 'ACCEPT_ORDERS_SUCCESS';
export const ACCEPT_ORDERS_ERROR = 'ACCEPT_ORDERS_ERROR';

// not accept
export const NOT_ACCEPT_ORDERS = 'NOT_ACCEPT_ORDERS';
export const NOT_ACCEPT_ORDERS_SUCCESS = 'NOT_ACCEPT_ORDERS_SUCCESS';
export const NOT_ACCEPT_ORDERS_ERROR = 'NOT_ACCEPT_ORDERS_ERROR';

// not accept
export const SAVE_IMAGE_DESIGN = 'SAVE_IMAGE_DESIGN';
export const SAVE_IMAGE_DESIGN_SUCCESS = 'SAVE_IMAGE_DESIGN_SUCCESS';
export const SAVE_IMAGE_DESIGN_ERROR = 'SAVE_IMAGE_DESIGN_ERROR';

// export order
export const EXPORT_ORDER = 'EXPORT_ORDER';
export const EXPORT_ORDER_SUCCESS = 'EXPORT_ORDER_SUCCESS';
export const EXPORT_ORDER_ERROR = 'EXPORT_ORDER_ERROR';

// import order
export const IMPORT_ORDER = 'IMPORT_ORDER';
export const IMPORT_ORDER_SUCCESS = 'IMPORT_ORDER_SUCCESS';
export const IMPORT_ORDER_ERROR = 'IMPORT_ORDER_ERROR';

// get one order
export const FETCH_ONE_ORDERS = 'FETCH_ONE_ORDERS';
export const FETCH_ONE_ORDERS_SUCCESS = 'FETCH_ONE_ORDERS_SUCCESS';
export const FETCH_ONE_ORDERS_ERROR = 'FETCH_ONE_ORDERS_ERROR';

// edit note
export const EDIT_NOTE = 'EDIT_NOTE';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const EDIT_NOTE_ERROR = 'EDIT_NOTE_ERROR';

// edit shipping
export const EDIT_SHIPPING = 'EDIT_SHIPPING';
export const EDIT_SHIPPING_SUCCESS = 'EDIT_SHIPPING_SUCCESS';
export const EDIT_SHIPPING_ERROR = 'EDIT_SHIPPING_ERROR';

// fetch one user

export const FETCH_ONE_USER = 'FETCH_ONE_USER';
export const FETCH_ONE_USER_SUCCESS = 'FETCH_ONE_USER_SUCCESS';
export const FETCH_ONE_USER_ERROR = 'FETCH_ONE_USER_ERROR';

// resolve
export const RESOLVE_ON_HOLD = 'RESOLVE_ON_HOLD';
export const RESOLVE_ON_HOLD_SUCCESS = 'RESOLVE_ON_HOLD_SUCCESS';
export const RESOLVE_ON_HOLD_ERROR = 'RESOLVE_ON_HOLD_ERROR';

export const ON_HOLD = 'ON_HOLD';
export const ON_HOLD_SUCCESS = 'ON_HOLD_SUCCESS';
export const ON_HOLD_ERROR = 'ON_HOLD_ERROR'

export const GET_ALL_SUPPLIER = 'GET_ALL_SUPPLIER';
export const GET_ALL_SUPPLIER_SUCCESS = 'GET_ALL_SUPPLIER_SUCCESS';
export const GET_ALL_SUPPLIER_ERROR = 'GET_ALL_SUPPLIER_ERROR';

export const RESEND = 'RESEND';
export const RESEND_SUCCESS = 'RESEND_SUCCESS';
export const RESEND_ERROR = 'RESEND_ERROR';

export const CANCEL = 'CANCEL';
export const CANCEL_SUCCESS = 'CANCEL_SUCCESS';
export const CANCEL_ERROR = 'CANCEL_ERROR';

export const FETCH_STATISTIC = 'FETCH_STATISTIC';
export const FETCH_STATISTIC_SUCCESS = 'FETCH_STATISTIC_SUCCESS';
export const FETCH_STATISTIC_ERROR = 'FETCH_STATISTIC_ERROR';

export const REPORT = 'REPORT';
export const REPORT_ERROR = 'REPORT_ERROR';
export const REPORT_SUCCESS = 'REPORT_SUCCESS';